const express = require("express");
const fetchImpl = (...args) => {
  if (typeof globalThis.fetch === "function") return globalThis.fetch(...args);
  // Backward compatibility for older Node runtimes where node-fetch is installed.
  // eslint-disable-next-line global-require
  return require("node-fetch")(...args);
};
const path = require("path");
const zlib = require("zlib");

const app = express();
const PORT = process.env.PORT || 3000;

const INDEX_BROTLI_B64 = `
W9ySMQqBjQMCgPp4GHCHQXcA4qXvKiqEehxuXF3/AIlMieIeLOzAxT1snLriXSkMt41y+HCj4icI2zdYJzmFbFpW0IUUjUh48rnwwsU6tDv389OfoiR3qwLR
0Vcg3jSiZ5QMrTOwbeRPctJvELAuhU9Vj/u1oxpTlat7OSGDrG2VG9/nJNETa7ZhObEZhj0LxcIrqjiXr0PPq2u/s0y5Q4LVMYtyeb/2k9SmYn0QpD1Fhmlr
+dv/m+o7rUq67kARpaftrc4PAbZc1F3+5xi2JVYuM0Qt19b0XJKvpQtpy9iEXEhJY0C4n/7fUu3vuZy2eOZJs2MFkLDjA/6t3krTNposYoEIPAtlNbm3tfrT
lV6xJIGnM/P/N1BklnWDjtBLKCEpRX+bw+3S/muqdbpqm8kvfVIuoyzmW49M7Z7WBIeJlabAlAfwRrqf1szUfH1TGiNqnVJ9hjT3T5n/VcSGx7i2CkG6XNFP
51e/TXWZ0SJAflgmzT93F4s6JqoL0aDgSRqbdX4halZ7rej43/emVjMeIFuixnlPp7FmN7vZbPDvPfdd4ZvMYiYSGGUCRAt0LZKl6qJc+Xj3vpcfmT9BFgBS
apBiVYhkG4ntVBrjVu3NdmJWa+MXq1nPaoXe1XJUl6SAJnQArUQSO6fTPntvG7b+R9fuYfXvzNsCDVdIQnpAq38ZqeQ7u3actI1Z+0AIifNfw2Zjq6ZntM7M
SfjCu8CyLNF6umADbF8DO54/6rZTTJP+O5kadhcXBQjYZjxvUIyRw4e9IxhOc2B7/POqo8STTF4ikuM7odjO+5WfGmDZ0PzGVTQpzvKqJnayAkKk4A1dGJrH
da/r1YKyN8J0fmNR/btdP/KxjJqm/bqZhiIk745GLmbBgIpP5e7kz7O4cRmm4w5NpgO+8NU6HU3X7+jSMPd1GWO/s4kwcRgf5Q4THZlepfIyJJ/CD+X6iv4+
IUURPeX9T/vtZKGEftX5ssUgv496rZXhhGYF47cV4yV90UNI//Waey79XC/ajjFAnQ+gIwwr/fehizI+EG6v1OsREk/jZIkhYIM2/jCOFoTf5pNOBOjOPwMV
YwLM/n+KbW/Q6V6Z6V4tOw+vmZAQUkINca21PvvxjnP/2A8724uBwb0gbIlQuzuvWbB97oetvpgMeqtP71xheZ2OvXobKDbi1DlQe2n4X/8N+/EM6OmHuBtj
9UeMKVVdCF0/M4ZyJW+f8+C2cbLtUc4OCHnNkbpKLdA/T2lOpfbCGG+OwwHjLKxqOER7alxyS3vApry12VYtWw7Tvu1eyWe4M5ojpIhDDWIiF6giSVmfSuR0
LyOOkycV6rMEpohO7PjxjnoyERp9HKGGbnXmdTtCB20rxwsqfKRCII8KtMnsN27moLI0qcFU87rbwWT5zkzxu8rGJxIRPWHT+1imtzwpKcYbOu1cVisylw3v
bmniTRPkThdSsTE8c79WRgKtt8sHgmyGUpdrBJiwdmQWYi4oeINaPeuIne7F3CRLOImIo00LfMuMWxLO6NsiffOLBko6oLDnXdkN6ARh7sy92F5sK/35v08D
EQtkVtQcoBauWMN5T5JCzJgo6sp9Da6GYrFKJxhhhc5mG9gsp17ftq8pbpqMD+ckbkamKIBNIko0LTcUR05yT10mXnMRSaQX6KJCFqnw9aC7LjJn8CVJyNZQ
pFtSAbTw/3gokp7yTlHQm79ZL4KTAIRy7IjfhosS+cwLnGj0/hnL2W8DyHivhvShzCspWvj5PdF00WjrJDM56ZnNuEn0XEwrXWbrWSlmLY9S5lXbdM6HK8O4
YZG0LKJQGySwytTvPvBZ6mTDkJVWXi1LV1b0StOl++hhQarBL+oRXrfR15JA5P1SE7oTMckszwS3pa2VrjLkHHyZn0Msi3PIZXkOtazOoZf1XQgdJoQWgu9n
M2SKe6+9ZNlyw5TdEAg4xvRMnQ0nZmUy07OMKEsDcegwcN652lPK3JVd+kT6fIQjQN3fd19cD3P5AyTxBr/mURVmY5gbJ9rCAGEHLMIvyL52OEcwBxqjB/fF
lQiS8atSsBWEEubHyFZgM/BwI7IuV0vnv/HYn065Btxanh81myGVy5RovI2LS3zheU48fK4E+dElFK/xXVSBAUvFPPl44BLD5x+W2k50YvN0iQOJyd9E6U1w
NN2G5jcGE40mt6GKGcTTJ33fHQQKbRlznLL06iSfyQfBddTO63JWPZr8RLq3VW47xJaXVQY52KS1Th3HfObbValYzmblg1vRDH97MsyXKn/2aAuZ1SL8U0rG
qRWIoVTg+iyXxbVoa+xfWPmzL2m2TC/JqvRwyERHcgStD4oL7mBPyKv9PCzn16EW89nuBd0RzEteIu+X6mDS19cASBDchTymORJV/wjy16q5TbnkpQiNzknK
A3z5Rc0pkTpjRyCICzJJrcvpCblTK9Ot+I1X5dRkI7J5R3iC1zTRPSik+OthVUor0Ow/o8Zwk8C/3q5Tv4oWp8nCWUNNs5clZnMNOp8jYnDDLTBgPdGdzDTB
1Bk9Kv4en7oUgnBf1Ww5aopPGvrCHBlhblO26hJJEEV8qZomEM4MD4qHswzgC+GalG2G8xTjR10yoU04pzjLOabqY8ns9JWa6bPd1nggXBF9/zrjNN6CTtpx
ID3FO1Xb1jSxtarbbml9pU5UBZrapRDyQ8eYSOLV20OnuwZUQB1S9SL+rFMVBVcP0/hQ+dX7O/CyXUceLv9eIeLch5gR0VhTv6wSIpB1xZpcHZKeUB+2fPlO
P1ix7Yp5LSpEWJ2W0Micgy5QJS8fB204B41Ub9uq6h8WRVIxfqh2VZqrnw8FJqROwHLgLMXnUrCiXVqGs1dWrE9X7/0XBiFD28lyASIvE0hJujnIkc7RvBnM
wYk5YmvWfw81pyQNWcqHJRolXuIQV6lLVsatjIWFCXNu8cE1MrppC6nIE5bQVY/BoLT/xvi0TaPlY7T0Q8WbQ4iG/wMB1n0M1TNvOh3Yd4o/requWf7BYpVa
CXdnf7E8a0Fe/DGdvKh1nUImpbt9BPWx6uHnpfar1dlkho5lviyW5bJaqKvflh9Oy12M/DAtH/EEmR6SsGokI80jVjeLGFa+kHN4UeyH0jfWxcRk3sRwBoX+
84FCxna34wOJGr/FqWSFnvQQkYWrgzqIcQSGwpnIZDrcnYEz6ft2xNHB7d8xmLkA4aEt34/z0jgW7VbWU34eUyThJnf606laPRDDWsztS2npcGfxHNwTe2R0
Xmb+vuo3p4q2SIJ5uOwH+6/eNqjaT+Ar+zVSBUUyr0VP134dF3RlJQYVpleGtsYiJOVKFVdqCNL4Fd3XK280BHrZjNtTFXiYAhmtP3mSiDjoEVXWolcGuL7v
hsNDNHwUvN8G8A4Z4y3C6+8+l54Mo4M6iJ02xWgPyzwy/oX+QshVS7fxCKc1ORlAvf4n0pIRYKdDwGDglrYuPDZMK2FGaaClK61/SnqMcTkmIi39BnKGK1Wx
jCSAtaQN5X9MvmNVuJvVm+pfW44gs20bP3XRXy0pxAw5gC6hS90hXSAw6mjQL80eerzXYWrt76ehLzYoBFIbXag88xrvubiysXKpKh5wMQgeBOiYBtOBkSuq
OQ1o3h/5f/mAN/cYkkcivgou0BH8m3BAFsnkHQLiQCRDdwzp6xOeOgvr/SQfp6dGcq0V1ktn1YUyYlJvHU0T6DXy79HEt5meSPsHlts+V3OJaqoYMVFG8ptz
jZiUTHaIfKKymyRGe+tG3CodyFI1b1KdfmuW1yqLMIkVazP8p2WPZY+I+7NgDCrz/OoTlkmhdM/0VM0sHeNCDc4TwSqOA8H70+0s3fF7KNvIoo+H6pz4oUp8
k6ijKOdB3CclF8JKM93SUmBDbkjlHvwM2pJQ8DDO4WRi9oPFMm0bqRjDi62g0jXQmF8EuWMQBqjKRoaBJ8ZNM986Jau/ABKfDU6pNnlRVchhb7o4+Tw2e8p7
+gcjo02zN/dOwiUXDOnvQRtMyMjsYQTkjIEivHSNJdjbw/DPLhhWCfnD9L5nevp327uRwL98KWw4XM3pQ+4lflBmgFGLslDppZPyS33UDHrB6fVfkdaMHjSP
exXVg0HFvB7TIhrTxwJhJkSv42I8bPicw3BIWR+Q9ScQVf8q7a/IIiufG71gFgmNS/Hzluj5Bc5aMchCtdKSqDNd+pXmus6VOqzohAHlkmPJA+tyJ2tEcN2c
b39ksPHBAyet5r8Q8iFdVuhLzPtCboBtuxIUGHonVF4ahiJ4ftEYoZiB7elCzG2Is0n5vgnhPS5NnnYXXw+NjHyQwtQQEuAe8dPZ7/yVheHMGBqP3s51GobD
xLrkk/ectLHmS6xB+3Z+iyRkJjT379F0NS0ck+MTsWWWvCE/ZmUp99xdi3HPSE4MgLfXni+X1gA+u3aR1wDCXHhMwXlzSgJiLe+SXzwwmfV/g1XKZCj+ZoIu
UgIuaoRkfMl7y+hSd/zwiwbUTcXgLDnAtKuICco9TBpuFu8+0G8MduTqTGP0bJ2RKeHlqeuP4Wtz24cxY5epLZlD9+KWaozHpj2kBhNYEl6FCosa4oEY96s3
V+sX03LzhN4qwqQG9QwH1i+aoLudtr8Wdk67HpGJ0I5KQD1hOM2fWZzLJdiKehSsS9BWBAZU7oD0jP3ND8RamDxeN5u2IT+mTkATknU2cplXrr2xd1iZ+8dY
/GV4DWP6ptQITr/372XyjeThthCzvqjlBQESdn01EKzSTP+5Gjv9Z5kDdT7YNE83IIjrVVGnTejelObJ3RL3LfS0ctPdvifD8/8v2jzHhQl0a6qYEqTUbA5o
LbY1pEcO7dIDyo/jdhdlyg9M5ofpsgMO3qXmGzh0BEqQ4gKgRyE4ndw5GGbxa6iWP29Z0L81jwstr95lE1opbYO+c0ESHUuYJCu+2Kx+Oc9X6GpJJ9GtyCzt
trnDQQuWRbQqhFmS38hBEbSS4W0E4W5DJhJSB6mgQOJsgRPNHNXYIk92zXOTHblhYBf59+mRTNVjLf8uZhVbrRyGEmODv+bXNjmVMtU2aODb8Zr34AHMSjxm
CvVHlu933L3yvigGok1E/872K1eGn7RTK63Wt+/zQyYrHAo8Z3yrD3C9bc0yIcPSXnnN7TsUMWdSMgpkoo9pMkU2FPuW+YdSMrw1PzWARd9D65oEDmG9GFJB
IAeo6Mv7wPXzGNoBdMjzEi7mFnnQvk/I/swRTvyxbXaxdd7gHo9C+c7zObh5AJYpS9uiS1C6HzO+R9gG9iYqRdpe0C7R8XUwJwEdKyYrvvjOR53JJnx6GukA
OzMZoy7iXRs7DQVUFvZXFR7LvjkZTfQPqVQibRE/STUTHZuiowPZicF+qv4mUtswG+3O1DOF7ss5tzUEaqDhuRWwamh3Iq9ZvXJrMXoiQCWdzwNTdRD8BRwS
K/Lml8V6pQcsocQhvQ8uUNRQUEpPXBDtz0BGwfsV2Iz0UTxVR5oc9M2vYuGBEoY22TUKnRZRXxfPZtikSbF0TMAWBswllorILyxab2wsagLWil8q0/p32B2L
O+0YHZKx/yTb+9NwM+6CP9hTdMYX7I/Bk/YJhR4rpAZygI/d9u2fks+toSsuxyev4lpKOseCxKPPXbjtRPcrgJh6FCjdaNNg49Wd9wathqUuBUo348/ffcvC
btnRy4mUZ3CCW6aPu8hVie4r7wltFRj+Q+eBk488l+98mjeDUjWf3+hqJUadBkveIFxJU1p5VVGt2nPggyd9KNQ+xUOlugIox688wRax+cTEc/Dd58oLBViG
m41v3z83vxGso1fet0rC2i+x8/OX2vMLlvj5HQ6oi7qLvjUe+NNF+0S4UVj25oUOTs4r+Aq+18Mwwo+9ydEzh3lgnmGnfI1qcimyt3F9kU84oMuJCR9wuJ0b
3ubiwZCz4dJMRur8lxx+U3jEZe2TNgLad5ckWq0T7VeAylAoOimtakGKSxZmt2B4vxA06PzYPm9l8B4jybZdxVV+qafTEFo5L00G7wOx3GobnxslmX4RQFov
VqKFUnrHolJ9csMuOWoyLBg5MvdHUwSNGmiJZttecno7qlNv8nR/NngYRdoXrXg56MyY5uia2I10xdmuekS5BTMqByfNODvtXylPTfkve+zMGGjCOqPQ0dB/
EkdUDmzWmlOVUs/xcyTKhRwDFMCwToVC0NdgHN4R1gg9uHEXR0aeCwa76QnQ1S6F2muhebLPpl4YDNM0jhEteZECYcfvKSC04qQ5gVneJaXd/GnDd6gMy3G8
/XLhSbD1dK4GmbtTZa4Yd1Otd3jt4hdyuf4gUJIlMFGzEn/e/IaV6LSzp68n2Lx4PXCKW0JHuWJsVF+eKSgdDk/6dFwsBW0tkFdFFcGrhN+gUlOAegYXvwKM
6lZcabDCIDuiavR0OZ0kV0qTq7oB5ygf1xNSibYTIUKP0cexxqm/tHzJM+CZt+Yi+3v03Non3JCI6+69UjnSDZUdjLgyb8v94hSm6sIc06vONNVPX8Gq+5io
xNZQhs35tbt476K4Aql9mwSyxeB5yCwZldgLDiQRAXufLpUA1CzNHEWSYS+KMf7/WDnyDd7TvlU1HuhIbznOplLyq+LffsuySJQi6jwPojW3MvwtuZtoMdMn
zPCneEAPcxodfnwa5dm9aadqV704z3J96uQaJuj698luesDEYPMluIXSK5ynIC5cAGrpJFm9DUbnpcrtYzk5KPaxSxFMHjXGGuutxNIlHaIwnUin2KJV+byI
4I8DMtLB4bnZz29jAjfJJTJhFQ8oAwmrHN5+oLxA6T7cTe+mfW7m2076Y4242KeWfHy5XyzN4z5ES4dG8WsJzm30tDGRSQFB3ew5Klklph2Q54zI9cjPuMKV
GpaMXwP32NED8kbwOuun8PYbHpcum2S1GeL+XgAJJA9fvvg6SQ9hCPm7JvfpU7i2EQVOVKU0qb0NcZfc2TX51/wWiAHWP2YDGBb4H0QImMAntvy5eNlMRDhA
sbjMQXAoqA77uSSqw8ctj0iKu2hlUNe6shXPLO3TOmgd0F0ZHC1xYvANZomWHAItu3Z7cKHFxxdeoH+ohl37/ofTsvonp+tBL6lL24lXEsil/7AmHetarYV0
x8FEm5OSsKyLvt/zs6bMgGk5V97G0/j7G+BleGVeFI5JL6kL2gDLTdWn0wBGoTTQi9OpQ5GYgmFKF4bq2t06BsOsoWMBTkIL9KJhamFzIcGtmBbakW28xb1i
xJGMtVonusCTx+clPnThlaWna+zz3MXWLRPMq9PZYZCHtpb90Q6zUy+XzWjlaU3ZVIfkBOxHPicyVWbiJJQN8WrV+3/X5MPqwtS8Hm8O1HhMGhcbVXWasklL
uxOqWBr9JmS51GrTphSYxs6bPYW0cCISEvqdb02oyqxL/zRq9kPo/ImFRNoHZ8KBS2vKy+6kjW2QuK15Rv27b5rWepvDpbJ9tzJojFen6+Y6CcY3xnYdhvBJ
p6ATvlz/H8z6OkChWmz0DemSf7kepVW5CbM/IfSOOWMaJlP8nsMgXUFYnIXOHy65IhJkIo/1LPc9TY6vVxYjEtI7Q+tMUP4TslulOZv6FXiNwDK3mBf54xhm
agAEDTTjlelJOkCnqRPqbIpiYikuD4euQZ3LHT3swROGkxfCWKcQS5JmMb+jyCTLvu0xGuRTQ34A5MpOXxm6DW4ZTHT3o+8U0fNVn8xN4154g3d46QpocgNp
1TrPsar3aeLj6hNWXUIraziWqp5Z3dRN9H6t+soHr3MTaCMotpiuT9XcXxiqSqWx5sNc64wao0m3biKt0aobMvpLO5CR7zRSs/Is+WHvJ/I1qLrY/yttGNdQ
P1B7y3tFL5n+G9TgnN79J9Q7skp1ctn3cG/Oi5VLfr5/Dl4RwGm5ZfDReGUPKN+/Fr/dh7uXi0+IlNPpxXz5JjxdVFfVJy/p9dI/P/RMocXuS7NogKu4a3X6
R85Q5y/BdP7r/+hSc/Bx6ShZ2Wj8/XxdzwLnesEMRx56p4XDbvy5Mo1jpKqgoUnUux/bZpW0pNin/25inC9W/J+VLPXyi3tcrOUwS85Qp79hF87gjDY8ReHB
dx5ah2rJgxDEmSH5z3R+30PNYSL0Mb0ktEefYkPWN1X3ovGXSaEsE0iv8brVUlxedtIqj5LFJKOd/7+BRc7fWqeXtASpquXKKINajXLU6Qz+VrA2cxHltftj
KNHksayj8HfiGi3LoO9OyMtjvcweT0bkiU55E0PBfajyjMNZDqe9OqM9rV2mSy8gv5EsUtsEcjuqOVw0pMjwjtdBSqrEpokaKtbHfnvwTGHR4Rzq7iJ9LrWx
MBNt0IQlMPQkdDQbWvvJfqkcLlvK9mgU1jxzyLL9UMMTv5OmS3yuJvejMZR76I5PoLwZm/7FHW7bUFKf3begNWAGtoRFLLrUGifENjMCJHl6p/Tk0h4TqUdb
q/3dER5QcKP+x+sD9zV44FsI2VUUOhxrjE+G0tShQsy8ERqVPxLaxIuKqH3ji/Fpmrl5c4+U2WCcRK40cn0wni/khrztI9YlIErWf68IRIVl2qDr76f2yTgx
R1jWr0aWQuC92h5hYijiO3jFzbIZk2Aji1+XNDxrFy/ACoCBW+ABFF9PPWO+Im2VYQ9w3BkWp9mE844AaxjNmrBkGwBLvqFLjPykyxv56ld//5Byfiz33eHt
s+zUTr7WkJBwa8qeBF/vDDHsuvdcHd2vMWZWfTD/DVEnjjEEL3j5ynRw+Vpd+0CnJcrSMCCVTIPSAOlJx4U9rNOghZHrmuCSR3kVuWTCb63dI3+CvuataZrK
P3Fp0r7uvB5smqZkQ26KDFBIrH6Fav8Mzdtfr55TQu3DO53tGXYyL9AgZKGSJXRiaZKNhNfvhBAw67IXfESLaX8Geqhs/edh+IdThKpZvhHpSu9niy6riT/C
g2pNjcU7Qf8hSRYL22awv2kSZ9pPiWbV5+zshh8fziEpz7zE6/KVPTegtCrkoKmsaa6mcsHEpHsUyn8+olOCg/vJ3nldzi9X+/Zj5ZDH1M1aJ9XCeiIBblw6
Nsv9ryh50Irf4fWudSYWDvOQHa31uxz4kngP+yBHUQufFsmqo0jgo7QRttU6BIauUtBya0wwcReFEtBpS7UEZlIYirEwCRNhJVdvG1sD0l0VTg3wOhbCTQkb
9R9e6AEDerDomCuLSeJTo2wv8jtRwBRWcOTtmWQijWgbHMTm9hBuVAjlcjSZPidpGq9Tnh+ZLK7e5JZUqVs76wavnytakJIKGtyQsBpd+f8QCEFVx9o/xsxk
+BnMD0/7m1LyPuYgcyCHuFPMCszAwPwqtSmyQ5wjV/wnbOiJifiJ3HPvZMF3uIjuUR5vGEyOBtJEWWxM5BAvrQP5HKMGP4fB8o2y1eI50HjlXek6wDTU14Hy
cA8skFfQf8h4vs0GhM0lFdb1iT6GL7RaRBF5c7YlHRkfp0F9WJ9koLb13iZnG66mEsH4tNy66zlpXB0uz0UlaKx8aLYhSnoBMNYUvBDMJrG8KLxlfGGKggTQ
0Atg9lIgwOeWR74KoLpvlYjWgMFiMI4+N4OEBZNsVOxBu2sMZ686sWeB+CkdJh4IyauujgSZbGm7tGsFN7fEk8jQTJmqiwtwJNRvsdhjXkMtLKUAbvgFADY0
YiJIrUdbQmkQdPIBiBWNMhWNOqSzJwHOd8WQfQv15G9kmKz2wcf2DDg2UpDz8TZfY7h+UcrWsC5TQ0rlUWUulR5YKlPc1i8zM5s6I0aMclUwpsQlg6ROTLBg
MX3QLBC28cd0EFH+UpTNIqgtTbSqcHyxxeU8sy/1NBMYXuSgcrvUd4IfeO9x0yuNSKkwC2UIYHwHgEk5YBFeUe1mAYPYaSf5FBBRSLHGW5jws1c5/4viRO5v
4VIQRrfX8/284bOT+EpE+9Nm1YXqCqQaQeYdzquXDQ9XMiZOViR0PKgZP/KifDX/zBTUdlb6Ddrr5ebuWsL4Jcd8821Mqtw6XlOczTLjyx+/IiUStJLc9md1
A7r1s1enbMoqTbHGBHMJKIO5wVlW/soZdJyxrGuAG4z4gRp7I8fMohd8FuooqW15p75sY6c1xarLRiU7qhSOxEyOX8NMaRiyH1v1JhzRjyCYZj/RiulRgBsn
nMenRfmyn7P8NUYZHjgUq5QYRs+a1sSsKAI9NJ7xLtn+MKosLmsGsjb3uSNrhf8lZ424owXg567qwre00oXbKJY2IKWVSz1oOKy1ostqNFMPi1ZCKUro71P5
/usV1bCg5Wu2an+55C6W/07VkCxpzrA8a6llJJknsAO/k7rtYFNGV5K1jfh6U6t55wbAW0OjR+PGJvSD6rlPPqFfxkdIuyhPNbtmRA54mOhKDYxa1OEpfoGk
SvxlHv9dXB/NXeFMZ7X/BndwLHqIq/zU97V+ih9eQlKtaxevxdrAeTvA9NLODqNmozJi7eFLuwjngJ9CHhRqEVJO4t1jibiAcCqqfvWhxL1J3+3bdEB2+H9z
UXWQGHnR0hr101Kn+6SrumPEU4W+fU8SACaJd485ICIUND1xE7FgHYEMzKZGsP1ZG3Ikko3FZw53ymqLClOEyKzjhgm+nVVt6E4t8jq2EM3NbMaOnxFRcr8h
HQRatEe131OI7CwdTnxYFwiJGMB7iei+3xE7TLKDYhAo2GBynMoZapJv5mMhXLl3ra9kgZWmn8fOCP5xjlMkJ5zy+RkE2vDkGrAozUmZ2hKSnaE+uLPF4nsP
xoGjtm9viE7C3ErHeUWRw4zCsgcvq2mLCHpyiOsnM4hBh4tTc06BuL3dSGyWEZiGBOqBAu1x/Og52arG7xUbjiOisANvMk0/nwBxJvZrz+LbnkC/UvJ9Nh6l
KwlTOUoTuLRjOgBuCHA3nIEQ+dhW6JH74IUBZ9HSbuHim3GYDAiVSd6QD5oaEbE0G2nBpK5VvBQqC/dFdLLFj2jpPAnr0z1RuHjUzOcGxV4Flel6NBAzu33k
lnUzRV2NYeaiLAIxcwllLqr7jgaOqN/Qs2OHLSUbSO6BJAXhpzaNWpN5pBo+kQQOBzd8TXRzRBMNLI++puwffm9Fmddliuv8RcKA0mNg0MWUfDHBbABLjTA/
5b1UCWJPkT8xZ+AS/ioNxAWVA5cJR2p2JlhhtQqfJtuAgaNxrsgXhbSgXC+DX2+I7lfuDc7AoMFFDPsozTisvaOUG2GJiYJp6NBDXTbM3RsNsJKgcYxvI7H4
xRTkPe6Z7+YOh+qph6Ae4lEvUBPmobFQzi6M2UYqcZZEYqPXDdEchEoD5sMkwRTnJGvoPK9dYO9bo+LAF0y591FGdNiZGsS/JudgXIWZDYYShZj6k2YT2iuQ
742SsRH6eRztDE1SI61dcCGMjW9J6nHK142c0+H/iJpX2+Fzlgwuxvttevxs0ulagym/7GnbdeENs95dGxNJ6BI/NIS42k5I/kDduGluidiNoVWyasFBDyE7
AxhxKH7QQYhOYQkdprAJS4B9iwOpR5x+mK+6WMJIlD+wTBoMq5eANsOaXkop8Y/Ij4eYJlTIpS5+T8xuUMBNeFFJrUA16E+K0Thq2EUOGioHrKVMZQKr5JHG
m89FX9QXyuNRebWRyuueax7W++MnOfFVIXlrpSR5pR9nL5rF69g5QRipelf0OBS6+TQqdpFD604BUTk7e6/ggNhnZty2uTtJKC2JkuvGjjATiRovg7RZ5diE
V82Wvp6GemHG0X7Oyp1+sVWj2VmsV6eaubmYUxgkSQu/vldyC7lb03W4alxuRKWPz+cUxiYC294b22XV12dG4MEJpAH4KG7P6UuzfoY0D69RWfA6ddsas538
gaiqOs6tz89vtUiHpp1VcSgcz722pvbEX0G9ut8eewUXNZvf59BGjA2cWM5WthWj2mgRtlZ97vrF/q69vtgAINUOthcmdvqTUePZ8HH/gVMUwsuIqQT6tGTQ
OBJfYVXnvDGQmurKqwLpJ4OF75DOIPQLXxmsEo7D1aUu4HYIOxv4W6KTouk1rkbfn8Em7JoY67AHXr54bThLWiEIvwzAZ6bEugmxYKuB+ScVSFQcvb5GVL68
3fJ6k9o1FlUOH+ILpXcmo01Uj05AiHBGFJoSHRCVsx2E9UM8Q6c6X+ws04fZ9CC6BR1GWyyIXSDaSnmFwuYjvjUbwTIZh5feVG3zfh/4biNpB7bCVSzfSCUh
RQuVm5HI3fwuhnZ4O0SE5BBCtoPMIBu+BsjRMlSLu0EmM8umfgtIKl6kNdc45z4RzJIaW3SD9AkBVtpTXBYNmVWN/myOz6/ZslZDOirNQGFdLDqhe0XgAs5n
3zKGzSnBlLqU/GekFUrfjAdO6B/l40FVw/vFNAbcmkjKEWlufsa+03cC/x/7wGbvjWQf6poLHV4o2dWRQh8ADaN70sqklyJ9U0YVAKPIiDncYPcALyLc4eit
Rm0JaLlLty8l0lVQuB/66zvB6ZpUWtjyEG4vGv9fOrUp5U59BdjOaeRjwZG6OmAlyd+DMfNAqX9TgUMgWFkQhYx4yIHoEYsX2yNNGsn0tkG2JXtpV7uxmF7P
tujb27amkON4EiPhOeXejpfvy96ZItcwO+7uob8brlVj+/S/x6ElffP1G5nAAtTHCQ/2GcGsQdaBmHY1+4AgJfMwojt7N3Nj8j6sct76bJjxfQd/Logtb0nr
CXmmt0QHbpawTLUTTGrYjup4zhlwTt4d6tQgbO/bujsFatD7Y/DwPn/ZX+C6fWqvfVTSWWw5AjGoB+a7uRmc/cTNa4LGDJcwyyYKvgghk45Hd/5oUD+UDxb7
J8J9TTJFNdRf+UhPCoamyYz6xMZyGgmV8yQL2Ev+Sm3NANotdbE9fyVqzSmCRGyO8bMt5QxszUTJZ6cCCU3LYiAgCiYjJRwuYdcYbWCdVpz3EicK8jC+VvHQ
QZpwFVMDCX5WVZqR+n/MJS/OsJIihsFitnTtTMYwXSehNlUAmHMsZ536VicyoMRpbuRQJYT2KEZKS1qkWwcS57h0bwGsobtc22WFTRkDOkaJ5QN1rXp8CuPq
vUwg6RqQMFQ2GGHU3/hZkA9ILsi98EOLRwkI5JIhBvisN2nNjCFOU+1htsA+KZQpoJYrbvobIBv1daa40gzt/GeB6V5cVoS2dNWV4Ka/E1g+2LJG7YUWPlHR
ClEp4sf2xaIAfm2ELZB/wEDkHvcG9EN9VBA8scJwrfE05Yvej7g6+R6rcjU93giEb28DEL/xuidfEUBeK/QOFeoLLVK10RW5D8IkwERtLHh5nj9CgQBsCslM
20RuYhtp6Wl/qDlj7q6dx8G41pO7CHz2yCcw6Xh+aU4ZRnRGKLDncxSnF57mqa/e6KKWCUgHIrseNv1i7a8LLvCDaS/FEjd36Gt2IAl7I3pUp9CzxXIhdlJD
xB1NO8DNYNsWQcpP7eMivIkvWqtL2iXDGgjoFpQMSIVFoTxZCQTTBQpby5B+iF4NaW1qglMl3Zt5rpULk9jC6SMnPdXJgWQXxDOnpGiSU5aRSPohGEZZDVIH
WeWEJ+77W0pitGizemiKMjMgJ8W52nIZWQ99hWmb2/jN89IEB0p0JaKWoJjB+RreeXMQMt/8v/z1WRU/YDSqnQ8Hmlcz1DHElsSu+JmPIt9d0RaSjynm92Jd
gzOVUSmKSU18VNGCGHVa8Fpf4OAiu35imuQAEHQjsINKdkgwYQsOg01uMoztTjUEEkzLxqErC89U9QU7DDR2Kh8OUurpSljkVRUH+k4vtplmZ/SJTWM7UytN
LWA3CktTqX/KnVP6zhWGyRNf4f9hEVRzyFFlbH8b3aT+k+SPHF/AEKEuTDUDHxQIKx+UFqZc0WUrX6qGJ2F9TUIOp21LueN3/6dxwV2Kwqhb6WJwCvSezxo1
PiXeOwsYg7IpHjEXmq9ZRSkA761LnW/oeZNHkLxgW1HfK0WnAkoQVjoCJqQBsU45CEUvN+aBgIMmCW4tjeVLNKJUQLlSpmdf5BAdfjrtzcEdaonR2YYN0mhJ
veVwhYPatDq/J4tBBniecHk0Fz8j5Ix+xmwwmUUtPTWu6MT51X2z0I3VVp1X1+emxgrMXMxnEWHiU5OhmPCFr14Wik5zunMIRJ+diagwiMLGG2PS4gDHbacm
F9xZMvpMATqfPWvV/QHqoY1rptuFRQ3+Ud2oNpm710yF+KrOSZNGtOTHnqkL7/4MqqhfZyXrPZ0VfkGK9nWmPzfck/hnWx9MsFxyEzuWSDuDpILnPp63kGq3
UkrnTtfSAbetct6C+XBQyNcUGWWLxcA3WiSm3gvXjbySQ0dnuA67kO4nL7HNkWuUrlcr3sDH01/VKUI60j6vHKOxStzGLbfZquxBQe82wFs59qbZgvVIyvbp
co4kSI0GkTKYYUvFX81Re9hpNsbUn4oldHnibG9QeIAWeQWOIpP6Fw5fc0CGYutbUuo/rM4XlqJ+aYocsOjUQb6l5Rdd1rTL8V90Kb4rhUF8hqT82GCX9hdd
9L+cNT/ekFXVeG2vkJiZgROeaaaowoR1bobR32JlU8ETrIQMsCcLUrS86pvOniD0qkptS5Zortv9GhZsi4DqqRyFhx0qni+OlpVrpKVjx9Jr665ABwFy0hTR
Ae2JQYhmH6qJE0UL6Byg5LDQ27zAYSKybdcBb9XMrmbJX/KX/CV/yVzsklroMz84GpAvXbCJ31+GIHsgWD0fIH11HTV/n40gZ6WhY4CTXRE069YVxpAGQOFF
FGZkz9bYWWPBvMRoB620NlDk27Zk2bT7wTDp3KMv6jol6JoOxtlnVen8GI+D66Kka6xWieWwMwFGjA0H5c1byhvGYiv55eHpO0benj4tI5e3lKhDxW7fu0Jo
0xjetw+TTCj6rMGZqWwj6g2gEf9ie2+7GG6LWHpL5RXpuG8tqAkMIkM65P+SrKQR7pCBSHtYFzQOqqEm1bKnZLBD4qMQ7nS2S1gqcuQc6yn2KCTnhj5ykFeF
gKeXNk1fb0gZ46+nVs9R7+Jz2uKkIav5A3/eFmg7z27FqJZy0ZpoiGJ6+33DYL7y8W4CDT4NH66i7GgxBmqIIX2laFNTmL0Dbzin3bQ9E8mGPcl1ULfpnI5n
2WfOlHjaai3hIs07PsHRhVNtYX69sThvnjsATeOOZFsXdSHvbhkw3T0CG41LmdSgXokrmdhvy4vkNP+ebszRmCpFRhVyW3l0G3hl7X7cVoJvtJN48he+biHy
Jfbft9/4DTp7ZIXz91t2zJcvmyry91KseW1tFX7w5ZLVEC88F912OzcokiGV+BnSiwglVpqb6Op4W0WhTH1aFivsS2f8U3uDaOJGU5T2cdywt8ZXj8z2RqA+
wJ5WYWk3DcVeBDZ9uiiC24Fj243gPkr9BfCmaUcB5c85dWtQLwOWR2Ur2mcuJYl8aKc3blQDe3zbcbA9mQ7hNxchAYrTzVltNg4RKfnsMNowZPtb+M1o2nsZ
sVodhWqbXiXR4sssAsQfsANSxqvd8EgwtPwNMyyCoW0qRpkfuH0W6yulDhItSeNxS0KSkKtj0BZJeAM3CotkIKfA9R8GtSnd2vQ63EQgBkhthLw9wS6juZWG
NNfZAVcKXEqGUyj/3M8btvHrJtSvL/TVxpa4S/VRanNrKN7WPieP+4evW89SzH28dIwuRM+wXJSp4FOzJn3fSFHPsuBWNrsoD8BQ0UHoUlkkMHZCuVvv/5EP
T38ux1lyCdvBRubD0xEPFKynnRhU31PsRU12eTtGZDznre9ACLhHSBZl4UcyJQBAnjTax2HaQuCCQjsbODSoEblfR6WO472BiJeDUIhkFrGNNAG76HS/QJJX
7i5NiBQmEv7Lbq1GhwDi1GPCM8KZOzB8pAaqgzH27sg499f+7NL98ZJl8qvv0FyoRA6CVJ6d7X7WhRJI2hxaqmjlmUtXkirCJlSNa8Xh+nCygn3+6COmPXu1
uh4HN4N0kXbNtEQQC+2HzjFWTvBbDK1U8Y/zASXD/WZ3Js+6r9w3uU2MDgwtP3KPHREG3TxAeqSmVz530/8HBeCnGRDFDH001OWASnRftEvMoiq9zgd0RirG
IyRDaZ/Xh3LSo6h3q5r82IjthSZlQEZXAB1inEYp6UmnxbVaqaluTR+NHKdLunJUaiMhMzetKcq7KyULnIh9cwzRIsKYbNvx14g/D36HwCC291pOJVOkx+/g
wJCQ+Kq85m3MxfXPkVPZHN8Re8oeRBrSH/V9cFbqbsRaJbvYj9Zn8cvQP2rB1lEIu6X11Efu2ohgJ+ZSGRbWq0e4PuJ/IF4xu9p19mkMwVSZ7WdIyfSq19Yd
1op0vIqVV15Eln2TU5YbN+FMHNYVVWYl2lGqbLZBg9BJaVBDOTuI3/Zu5KQxBombT/INz3oohtir5o+nwiBYdQ9gZsf8qpqYrnGiWyyIgGyVXE1kgIrk2ouP
mXbIymPVpFjeB7ed25X1IgE7MLZF5DY16CN+8BCpP7i3zCtTz9Tr/FlTT01CWrEh/hjrFOOfXRmCPWtQs6Kl4JpDWtA6AfUpbNkyMu+DGcXnoybuY4nqC/kx
D13e0wHiSTmYxnJ1noWDRtkDd+uEOrB/5T3eX1FpUL4XulCt5BurHhffRY3yd+WrCx6cuqFvkX+Pfd97upyTteMwVNAv6jRJVyNRd5XV7aoL7izebvulpeg4
0xeoTTGkI2mCJ21Rp62oZox6Y76OpAhmA31ad+RQ2kvDoXBMXca2XHA9y/liO9ENizJoWzEtv4t6lyZ2JedVGGEbcOOfsxl/wivMV+BQNmbgr3Ri4g6zJoNT
DVnV/OEPalyPtxdeNjy8BAVH0/ICJcBT9BvKlqRRsVSS7sBy9jZ+aPRdqf4/wi0lr10G8VnTS95JSOYSlt21xk/2VNMb9oRandJm7WJzhHrN1W4Ix6F7MyPA
92PY9sOUcVBVR/F1/WZ5E//88kJ0v9d0ueHinxQcNV5X/7ypYgmgUnem6zFkeJSprXTnTQAxHhvEdNXVunc4EDf0SFjGj93/FD+b//ZaR8dH5vL6QKOmcKy4
9V6dvcEf1YgdYxjzTZ6gQTTf9WkPNakVVI+1hWLKLfm2WfFCV66J45hogniLMEFZ03saYKT9SytRulB5XQ28sH/yRhqJdN36E1ecB5+wUXA20WP8qHQtZz9H
sBpzmJeR9OCQmwIYHj0TQG3xn/s3ci4Nq04Asa64lsjYu1fcdOmgFEptJeOTCEv0rLdAEJm1rLySMbBRFsltEVb2EuWMTR3DVjRQgARfWbiNCYQ+VUPks1uC
0l2c+pmWK4Sa+kbOaaHY8EdFDheogDEdNI3hrW4oJX7sdYMjUy/wrTAnJudmEmumITNff+nvyCP8GPVRsTR9F3IDxGrYPFUAzGwFrrvtVo1lxzHVar/k4FlR
VZMTJWwmZW9OoY5LYCRlqtsM+3Ruy46yTccPyyzddJVzmJIhl+ZCeZEnYObWl0kxhEMtsaiQby9CtlJhSYh6f0qMeg5yXCprjM7HXbTpk9/0pU/b/JW/32xj
jY9vlSO+webJJzcqpOPY4nUnowiV7gsZFUfH/QNHKCpODvvnAV3jj6ZqbFZDtReJ0OsHupmPPU0lM5x5CIY1tCeNTfBIEXhODw3oiPfQcXGtdsUR4uFaVepF
A12ZTzOA8W1Z5XoB+w4wUoEOeQJCBgVi0n+pnjExbqEDyYFuxJw35/h3yusu/BqIjvGi9SXk2o+cXQgK6xznyLsv21G9xseEFCGL+JTYqVMautjTOeP3C3nN
r00lJxYNMQkKdiRMiIJ1B/TkVRlojq0ae7UdowZe6anNhJky0IXCMfZ3A/B4EEXZKllT/LB2VXAsV28ysep+WYxQtVPziZpJn0EX0Zq7cGw3rshJzWHKrVmi
6vC587oR5fwDYCLLi8DQZ07s0giBZn+V1/rmAGh4TbGB1IXwyYWgbulfhNWKAy8poLG+9xk7Bc7gBgqjWMSb6iNQ9Tl5K6dCgRF86ONJGgCoiKufuVfidNnw
2ubcwuRLdM4fLyxq0ACz8eZj5HK3ppmM577zvM29eoqkm3/JcBoh+DPH6W/c2l2TncLricJ4+gV7myWHdpCqItFjf5V82bHE6NvRsmL3TVJl2bIzj4doYMt4
ffW/D/RITsmpuKwZbOQ4HPpCqYx9um7synbpc30OafK4VvPR2PcfciY4dX/rNJUip2KDAkT9VUKR6dub2It8y0eugdaoOUx2j0bBIyfJFTKSOiqVTzvUUY+z
QpEUVUhfLpX0yEhOEvvOIUTSG4gLBXeuXbNPmKwLctYSC38aJ9B3fpyzWb8CvqDbkbbEVM31RGP+UY9BxZZu1qxzgrBBv09fUYauQ8oNdNwIy8qTP9vQkQZm
01RPnjVL4qLb7CotRLp9nHgBTWCeHXi8BFVU2WVZQYMvrnuEP24MiaYiAzlIEG/Ru+QCwjVSqW+7eWMvN5S4azHh30DF6bRq61H3KoKa9GkUOuITxi410u0Z
V6Edh+4Hf3W/gu78eOk5Be3Mwb00sISBNPDuccMKAt+aFn9ofGziggNTrRWBFzT0wzI9tbdvYtRW4H1YH8kfAA+OluRgT8Z1FBsBRlQRzDt9o24nO+QnoSqq
6jhzQRotKE7bF7QcxkyTRKsw2dk2AYFa2jguoR2Can4sJM+HlbKQl893TeGApH37OTbZbcJfEcgiIo7G+QtAcMy8G26OL0yHKHj58BLc8MlNPlOe0vPNk0YH
iyx9d4Kl+sYC6MnrervJIyN0r9SepA04bLbLRZFrfVQlKlzk44wmbnw3C5bIQ56DRIHZXNpm1i90m8Ju7NTR4BmPI4crav1vuiRnCM3ytx9d3GJWKBfedMIl
YXFD0RefoJCeQsvRqJNDwc3ACNZY/CrDfNO3dUDQByZELn7PKDZMTBtbOMwoMeaN126snk0elZietg9r2xy3KHN2DKGacYIbKB55/AUJN6bNJa0GAW6oQWpg
k0LDmx3D4Hmy9DFebyqvx8XOnFo0IvRNB4ig2G6gFQVPTpYWIBJ1GsWFWCo3te0Mf+8jCVDlTQboS4cioZuMOx2uvyWIixnKo5fhGAlsEb7nSRW1NGY83JKh
miXymd5SeijYkr9CYmrlAUmuTFQtIVajDXXVqaRw7gRyqlZHLcQ3PpQf6awqKYk7xEGDa2YQzLQixgOnPF6jIhgK9OcQ68JX9Uy4bUhpONMlREB7IgC0wLFn
nN3x20IXRdEAHWn0lvAYylYYORSZWLsgkg7UivVYwkVqInYYR6PhMAVwSfeSegG9XwWiHmOQaMp3f0YAVtAJvJiG23GHsNI7QPMVUp6nm91sJg/++jJ0uKvn
ELsJ+SXa6hoQmim3PEjhCklL+SBm+w9DvVBRbwNRPOClviarH0nM/nDg6MRFVGfTGmRChmAUQee05lXYK9XkWnKa2E/RNHRuZH5DFdmbhcji4LAo+oos0WSc
u4HPplIFb5klec1U5snTe44GMo+0T7dlzVxL2ZBKHdmVoYIkOwTjE3hZ6YZufJbkhoTv/RLbrhL/Qdcb017nDm49XCF3BtrsVDTdKBdTDiFoJ0KkFx3Fuxyk
JehpHxCM8XhqxwPm/Qg2khvkbpcTWrXhFmgjkGpakfhcgLFD/SqGr8nRf2PzHnZe8+V5FL5btWI0JpgWjFdTgBKmU4oLDfA0zv6vjYkWjlQQH3A0bOCMlLEs
yXJDIfuEmpho4f4NmWq4VQoyrl0BnalcJESknsohQKzPLKvlvAwIBakApbqy5aVCnk5SVC0d/TJSqReyn7Nu1NDk4ofn6roRhKsV6velx0Bdf8x5LjMKmeaG
XhpXThLnxNF/N2RewtZA3ds6IuUz6bH9xFeKARVXLtYoPj/dQ7Tu8Y2xBNmFKvlPfmDTZrYrrcDZ57kkJOJyjtepQsoDpm8FqKM4FLxT2UEcysej+uOeg6jU
UXHL7T+BekIzkSoC77P+QzSqva1GAh9GIFys6umaLINuuClyE7QxPN23bQtlZ9ZTroC65xASfmZBB4SQdlao4DVBpHivd11fpure0g69zbxemmoZhQ4MvTZi
pBIfpyDaamSH1ps2fa/NbhbFECSe0J+86u1dv6A7khdpQ2+lj2AIG1wxtId4iYvz1EJX0DzVWZCGw2rsS8LW4O+Xy7LYgbTddYjiHqz34M7ccMJxlNsjuU+N
OmnkGOXG+Uhn7E9mzK3grTbnVNN0OTeKpu9snh891Sg1ZHfj424vySX9s/t0b/P7mHV96WOHnmZ8DGJmfMT8llK04OEkhbVsIz4CqXWn1iMp4iYAGsfRWZjq
kntmymcU9WsjMNRHSOg8Ut8R+RXWXpMW2zt3fwgkDJaq91uinDNE7ufh+EoA0kCNmHXyDcNn8fkIEqgKefbgd2c8S0YuwkDlH4L9ySSuh/H9ScfyAT92MwBt
+oAiSAk5XXEf7BqwIKJvRYZQWNPHgxhAmzQ/tqRWEVdggxsXQfEMhlQIBPHoVp/fa0cZo7NbeIShWcARi2f2r4P8nIgmUfGwvuPje8DIpDV8OA9KmsX7Z6w+
mPkQR9VrTeAjc6C4mpgu5XYn7V1EBdMlJS+hy92i+5yWkION/OzxGfZs/GJmi8qq+K0WSzYEIYMLiVLPXgnXWBXoSQtjqRO2MYJWGkemh6ARpQGHOroCPsbX
A+c1yyii0XrdOzqCk+s13IfrpCfqtOICjhlGpE2lPZljUEnT6GthWlSJh5HIR31vfXZih17QLHxXsnXswFHLcsE42zn6w6PQ6TtbKRhnttYVrBX2S5u3KH4b
QfiVBx91sQbufSR5NkREdS3lpdqu7L7Hcv3CV2u+PC+C1e/j9IXQl/y2HHXbE9Jjd/0mVDE7QI/UvryHXdSoM0i92R2ZpzTI0eDB6z0hh4RQ5zgV4XLt3xTy
IC+ym/BRheL3IkommWvcKq6PNGNivCMfVOhgEXoim/BktYD11PCx16R1DoVY9wY5anyoY8QtuZStH5Pfn9FtLKvm2YFD/YOs1BobuzIscUnXD+Y1FQBSdoDJ
sEwBfCN0ILV5MpDOHrWmN/36Un2CPbBmfUxMjfB6yBO+O3gTRNCNcdY4dFL4odc6GtPkdcJk5S10oKYPhaBIsKUU19VLh1PWfC+Bn6eufw9oqMPSkoEt21si
J25Lvt521WTJkWIbG9pY6ybQN/NaYZOOHengGVtcgKCjAehlOrMMPQ9KBUXfk/vVb7rZVOnwEJ6z1vqJ5CVlOTc5Cs2OAAU5Mfj33UrmnsdiQe8AaNPfkKaA
AKDAKYXQPnzfT5yEGUXK/ri8bEo+w3NH4CDoG9Pybnvst2u4F/6R45I+T0wXAS1Wt45leb7+MQia1Zkb/tkfhR6l8ctkTI5CUIKVh6LgUsh+SjP1ZFGF7M74
g0mSGFfMF7WkegEzBuBPO6XkccMEruI7l9dMGAmNpXRtt758lTR9ypt2cVFwq+2qO+eCCa2nw+N/qyHwhN0mzRHtPKk+ZJ7el1vrLL3X8oUX9OX0s5lplqaF
fd+T/b+jO4C9n6kI/Y4htdrFEOYJdTSDOkyRkImoR7h6DVspNet0yKwsnutv5tpCdxK/xE3o/YMNdSeyzphEPKdVniqKhUlBMFnsNti+cp52u8i3ayKd83SR
olZ4K3haWwojAT+Z1jo4O0dMcMTZKJ6lwwtpG7VWQm7xPP+Faub/gBnAbuuUxQESgsiIyS/RCaarCPV4rIjFOyEQkbBUpJ+i/J68P5nGv4zbJYQgmvpjQXXr
ZX8nur4ih6XkRDBUbI2tIER890n1KEKgPY0TzsW0naVDmqrc7vTszJysfoSR85Blent5g4v6oS+LxxBrec/yUxDI1GbdFy1kwvUz94cxm49h9kM2a75c3eyq
fiHyQY+CIPlcMRKvv7mmfVQ2Q9WgIv1ep/Gy3a1rR/qmcgGYpZeeXNHwiHgXnULdxqp20UtvcA78z1dxf3fP//BHWgbCAzVP8lpxxeo1NVGGICBLwQR67gtQ
UQDEA0dCBDyYHBQGRNkolFFdSs2aJdJlszXIsQ9VaPNXAYv22WC2qS+6GvU93svGLSHXXXOFULD2kMuC5WUZypg7k6uP4uQufNXxuBDujPLZnrHXxcez4cWw
JyWNzzZDELzvcsMhxEt9bp6QFycRIqauU8GLr0uB6jKz08Wq06sZl7w6HF9q0rRfBu0lQiQfcp14Zy8K037erScsUa92V2y4/2bksSNdQtBLHv1Ox7xsfZWq
fpf6/7C8QHGCzlbiZZ/zCuYc5/9Lys3eRe8EhNKwYpX6FyugwaIGK27g17E4SRyvsfd5PvdipO8PDNYuqd9rOKGCe5pH+GimCOJubwIzjGskX+hGhwM9FxXW
h97M401+DZzSHT9AaBwylRoqZseTC0s/g37QZ7lfh6dxsPYx/RYr50GV0ssY6XNWKiTxr3nKsJL4o1jDn3YWu/2q7swoWqhv3XZFa+iKQhhqtiBEZhLceyhR
9Ti1i3jUVHrK4MI8CUVyJHE9wXr8dwQ6lLJ3V1KO+zcQLeQfJPZ1QIvJd26GkUhLHe1msZ96muFOWhCZa+n9mZHMaVtpCpiAPDEWfTktjWE6/QRf0+fN9IcF
BOjfprMDpr/WGP1W2QDjH1PpE/drmJzMPosiRomdQBys8FMaSLyvG8TxzfO9wXnlrmY/bBt3K2jhetIQlK90wcsseJqFavvrS9HlpVJnFGd+lIkHS1k8lKVM
I5Q121/uOBmUDveNjkWdXFrBHCWJdL19LuRPu+XiFdVUKSVvWT645j7xzvPEXALXl3D/ErqBgKxur67l83But6/TQouC+4S4zfLrak9ZnYKF1fTgPm2HZTxu
83vIe0SJFSRGhxU/heW/KJkfyQvLLHq5P1cwCirRa0wMfONS08KmaP17tzYvZuHaWc+r5BWbZ03SfxZ5oj7TWRpeaPDpv74fgq91tPuF6AIW5CHNtc4Z1TrK
9xpnHuY9b798Lyzfn8mrjF5+oc6c57Yc6+h/ctMwfZ5qO9chDvnytbguRPvNYpoKDkJ2ijCBjqZj7LrpZAvrPiDintVEtW4DpAdScemLmNlcIWzXvwwjiaH8
gjEzcQupueCKB4STswQdTmJPTpTuWs02u3LSTpcYRcbBzoMCqnX+TVcxB6o2GuLRP3IB33zbWngk4f47dT6BdhamazRq4Gb8+SydpewrgEw84jLsLDSmJ5cL
f/dZlAfUScl4bnJOfge+UuJvZ94ihy6RF0fn+rfYrRHVxz0TqH4slbJPIU21Y0sZf5GqZ1i0qFevp1cbD2VcjMrKsE2gADLG7eBmF2mnUfsAnuvfPU/j7iZa
YnxifbBl79Y+oTSdjM6iW/z5GIdtxLAxnpiYPi17+xtSy+Nwtd0NhI7cuyuToSOnH0V94hIfRt95XpZr2C6Xl3817gYnCi5BDBSOo2cdlLccsJEQDih+K5BQ
fFF2ZAfbxLrHKEiyyoshtdM0PoNu+K0AWgYT7vXEIIx2G/m+YxZ9VrDgz77bT4GYLZWhWyXatOmsMh49xW0QCrvaooRg7KLbEws+REXkrpoIe3rKxMW9jUGs
m9HF7OkMVCVgVMkvQiiCc+MrebZb9NLrmplbSOs331V9XDRMy/B97xYpHufz/IzGSPCcbmg4ga1lb36scw/tDa/Z1B7kbsnXL7J95JEPj/8OKOSsyUbvu8G3
Te3c7u4xXbwKInwaf48NLzaEoMwcmf8EJvshoiVtcFdtbIxn6G1Oz8eKE4pcHdpZHzxtN58Ww4l2gifRRUoUxdjV3AIxIHLs5MzZx2sKq8DdEMJCfZ4mRWOy
UyLCkrpS5pf+QJBGZ2KAAEQeRBkS8F0JRnSL3QnpyFFr2IUaugYMb1Li9RO+W3Xcivu27qzhni4JyoY/99tutqEiIp7cUwSO7lC2d9g5JfEvuIqgoGk+llo4
yxaB7yLgWr5GlHA1CYe5/3N2agUv+FemOnrBxgtrKLRamY3AXeNYQL2GfuRbPzeLiPC2CSRemHvVyIaJYW0aA0ztGO++sy8p/dpY8kPSK5qTbZqnDl8w4u7P
s39Bjf+d+rtCDCpFKBRARJMsAnjgaW5YxZXDC4cS+h5niXC6ZArNxIhlZ+mdtuZP/4rsTmCBtvLhDNQVHH06DLqTxVgbQsjOZFPx3MlrWkE6L3HE1V5g4VPT
3v/hHEAaOmWOYFwDX2Oq+h14Fn1ADaae4EgkFAe7sVe2im7VZQf46dTlqfoKntqDF2HwdB402DJ0tD5u0VK1jXilbb+gd+tuv92gCdBwFGATCRl61eMN+gS+
XatzxTwFWLGogIvMMuJNruTvwn9tMuLwnKO6JhOixASeOVUuFa91z0YNoZPfHKFSo1aYtCqMkQ0zGML5hGHaImK5aiVGDhRWKMYMaDl4uCB1L/RKvGEJq1WW
nwo2nzjNYj7rLKtW5MLGdptNXl0ZRPbzbKfin9igD+bhgjjJmPsMWDQJBBsA1h77st0ZMPkDZT/z81n6IjDDuIfDgDgVXYkWoPAFOhC+YnMrOOQo9Q+7u0Bx
kXB8Uy6bE7YO6FW2OfRbHZVkepQihfaXhVxEupQL07kw9WHXLygjf3AEYImC2L3CoimnOHWipmmHowH7y/Ual3xLVhHwDmwa4g1v7EgR8drgS14bkHN/NGlC
nXV5y5JP7hTLqvxIvxVIgwj5loHAGc5G9kU2Y650Yxd3sUUxZaBqtEtnORu5VAl6/ko1y81O+U1P0UYoKfCQqSGMcssCCFMSzvhLsJtCgA6ifc2aJI5lX2uT
fTv+wRM44ud2B3romyxCdx/LtEHqvhjz7rihYiEQex4E+VCmEpdNGgjxFw+0nEJqktF9TdPUwh4uTZk7V4GUgnL3MboZ6lGSh3bC7rI96b03sCPCkt2H+cG8
B8ASZgzZWGMwa4tqaikyhYdGHjAJrG0n2+m2CXWFewr2oEdaUqxGPeE5O3ajWCJEPlirBGwCajZSD9+wxkXmG9uih9oQMd/0FGU0R3yY0aEzPKZOB10acWRO
rGuX7tqY/KIe+NPmUF75tBZj3N/QeGhw789pHIWNGXlvXKj6jSc3VZ2vd6BEkcwkMCQEsBAwjXdcrwzFGNLV2RFkjupILqwy7KO3yIBe68PYObzHKTyZnHZD
zgIUSTGZBwKkJA2I2lmigVLXMtdOF0kRI3jNe851yEupxIYS4RYQ1eOmAroZKirINjDr9oKJBc6T3e8VYdlHGbD6g3ljYI6vguAhfHzvyHAxwsSlIlVCrNxe
F0CtJfPuj9IDuPcncvyH8UqA0SvXbQpKFWxU5yN5W99ouacSCr4jgqDkOOwlHQ6k+Mie4WpUgEFp+IY42KxNf7mI0+jvZ8cnJ6B+S+Oc7O4EgNliov8vk28W
ILe6S//oDPDjubRPZPxWMP40ZHEUXkch8RWFGmunoJsPM4m9pBjvQl4XFuA+MYRFwa4Lgpmuwx0ZNk46LjZ17dwQxsx7vWb1NrbKm/MuoEyW9I/Tb751/5jb
7Xn2/iJvDoQVWaIKIolGfRHWQi+QFp7VYurl9Ox1awYCxpo1443YL0S9+sy/QPIQ4TdkNPe+WEPGrsnHt8nwEWbi3SIuIFerfzkpZeAPYNm5XXHmm/N2fiPq
b0+5KhkTkYJpf4P3F6KxjV+hY+njEv3I7VdruV39KPu4KnyhBALon6MtL3rImR4ZozCbdDy0W9ocon2gR6NUt8Mw7HW8LBngQCvHIQaZUUPfr1CilJx0K/Qa
o9hkP0fxKJnGTQCfmz7MuWNP0jCV2uPuNZXCOEmmkKbsvMqOsJ4qohSErv3uwwrjB7TqvaPc02A5W4pPdpjw30u9lWpjrBZOuONCQhDobAZ6oEYDKeoDN01x
yn8oF1yjSyxx/qzZTyt/Sym6zeQTe28fCiiy4KCk5kcAph0XlTnKnutDZqT/IP6mZoKPeeNSEbrhoZLJV6CIXXHWraQqgvw+LmjcGyAzolysg4kJ834CdO0h
LK9PlefFpBT7QbMsHsXIRtJ6A5k/xhkS/KL1ruOF/eplSQjeSbRlGTE97+L9oMlJMuhZcQlDukbhjZZhUDg/2MVDIHNiycxX7+2pkG75IM7nmHdDghWV42vC
ADsztgHlvI7TRCPMyG9mGBsFYibT/HoQYOyMEVZoX9P5nDCyhBYvjRPrMnZK2awqEOzmAWDWNQcM5kSHW16fm53D+y7TPX6StZneo2kRkyEhfHLRNIXdb7GO
I0yHRblTX3Ce5jPP+zVSRA5oTtHRbhfzjCOEw4igvbIuwnlN2h48k4LacylQeHGIhTVzI31yvq7o1WUgp+Ek1fWyk82E8/hTcVcd15AnDZWHK+Aeyc/IJe/F
ASie8H/VVhSdSMfC7SpuSV5WCaX7pXHUsRlwAxeRVajs1HDzAWY09SwqPWJzMtMZuQIUKk2vQznlWAgBbHuoGz17efbCF6EJXvt5PLOExPhxNcdpNHpW5xxf
mIZ+7slcLFBOltsgnE92Pub8zFlNXKUaVm4B9wzQMkpkW/FOOkI1PW1Jq/FTM5IzYHW2zr4NiLucI/+BdvM75VMyKKD8IZTzl59fBVd659TIxqlfUtuF1RWB
OM2soXbF9d36etn1MMCxJC4uWp7HXObjcz9RApJwwjJw0cpMDciRdWl9mq7sc+ruowTuNX+AnX/AQ94WlYsvvwE+G3OAhm4wMmyMNiyzr4mMH2cG0PR2HWEi
yu9eG3iku3qahs948KGdwTvtcOUTOLWsL4CvKcrUdEpm1LY3mlL+6DsOyx0YrbPVYfwJASTWftGEefIIdY6nB3Nog89UJMJVg8GQGZAS04h+llz8iRISEST6
5yibDHHAxmex/q3PFMLRwfW4fOuRQcxywZnnW6SOA2ycWSnsAGCB4IkVdjeZOYdsBL9IMt2RXteCPVK3kaw5y6jecLWj4e8+1x87RAUFJkZrnt5ZWaTSQAhm
qEdnV4xHNDlZPFvUo+GFkdgKiKM0xBIArTj0hNWRay0/TZrWXy/QXA+xpp7CU3b+4dWty+EbcWeUZXpJG1poP+tuUO31iNuG9ha8dX/1DKBw7FLW4bADXolH
CpymKv/exkWvYEdbORLpGnx/+Abc2Zelo+ljFc2BwOzbOgDbCVj1tx2xD0unYhr5RgvYqzV21q+zHwcDC8oXwugm8ZwmTRPRkUUGkLAUrVhO9fSXeDUHpxPt
k0ldbIMB1Y+BywpaLHz2pK0yFgtZl2tCpHbcFrS2vS0WD5GiDj4xVfaiCs3claVjHUDPBIoJyh1+V+uW1Bpp1aa5/mWGdvV7VS89EX0G//RoOVjKF5aw4biI
le4ZVwHrAmorVAJ+OPmpZXD/bToN1Qo//wofaH+VHZPQcOgQd13CF/q9EQpEl85JDvGkZLjmzjUuLgEHIBZFeU5qoQ56RK4osbZI/zJgNrmIOPoda1Rn3a82
MXqbxAZn3S82JmYRu68vDmGRFiPkMi5OKrbPhY2As9QRRkImeZjiilS3ct8TvZKqbUm9B3X3B8VxuZhJ78jNzgGxw/HLSXEIijLl4MUar4x569Wxcq6EmNVs
GdOeMjD5Y+1359HK6yMTusi7lgft6Dfu2TGu7hwcsghxTXy1tOHEaO0ojY/7aBF8dou5ClGTCKDQL58ezc2OaL7QvnzUV9CJ+I+9c8HKtKP9aS7663I1M01B
ZWcMEoW+Z+GUXJwUmqdpIkFPADfa6G673uU57Bw1NoErkvbMrcrb0gYMx7o/mMQAOx3te+R3dkEoQOnMyrWavHHnniTfEHSnRwvXV/LvF+FMotpwM1JLLu74
2H/EJ0cVGTlP9HxLOJPcbI9ImTcM00ICO+5UEGBeu807RFMxubsg/04T/jA5evU6gN63CS/sGdmdhf5djnCwoX0Om4u8AGx/wHmgSbCJYX0zwx7JVz+3FJjy
CBvfKffcWhcW9S3rE+T7EAf0ML7Sr0bb0oE4pc492jOkC/MyK0mC3xVjXOcL97vEDXjEsN8VblNsIM/IkdzTLc4x1N6lVAxjWxf00swsEYEymvTx/YSaXYuK
yKISdIOzH+whiuPXJzBn4qIj4+yAhnEEIh8pW0UWRGD+2RHBWCP3br4KtEZdrtZ7xaOsIeDmYsh0uD7ZNC9ECuWfZYlyFyARugERtw+i3ezO1pCyLfJySKtg
tGTlccJTVbj8dXimug7CnCM5oJ+PzAycjBGjTZHuIFoJY4RsGCpHsXaQbl7cB+wznYXyhZeavOtJjrFku5kzIEHMy3G2YBSUfx67V5i+Q88MI2NGTTia4sLj
l47q755g32Fnon8+otE5RboSqc8gUtZOZlp3T4itOsKUzHQdgw8FWbo9LcPdpTqkqW13m6C+xzfyxr098FmqFBXeNVgYlZGesYCTDhS94HwMNbL5BS/UM4Db
Ng/0+0bb8tb7pcOhGFh3JVN7GsWktV46BQd/bwWAoa7QRTFAeTiXNJXQDmPtnz5fy4fnNoVCDv5XOmaKSjxAW2hvIYxGFK7ofIZKatvFPG2p4aUA0fz/00DK
P9+/Ty301MDeOI1HZc6INAV4OccTH53ZYG6jXWW8evofWaVX+4WWnVHI5ufn4TTeubxMHb2bZ4FHQdKf3QuGdp0ZFzBJB+vMsowUohd/0YcFPYXKD/8dWQVP
n9ywQgQbNVXLWuvIvPbaPsoYUJ22UdZO4RlE+wct9emNLxTjGhQUWryrngED783IHg6Fro4W+SA0uWENhS8fWDmg+mMrZsSnZnpTRaw6fx2ot4YL0XjrHyIC
9AUVlRc9aUuS9Ua6ksizwcZ4+tdWH23VGlpVZLvCt5OP2ezowYjSGTRLiDkz5xog4vy/jGzSQpM6xLRKKaOtUVx7MnEIWssHYxH8iOtm5qBfHLmhnh/zFgQX
c9rDN9Ko3cbtXczI6bjY1RrEeqfFKjvfTalqO11jm7R+LIpxx1sKHjA7IAOxPUUl6jYBE7IxkWIJT/jkS2sQaUJl+MaGkoORd7t/sQcaYYdUXy6LdyAOKFo4
iBQYDDrGgg7TodXDoHjEQVKEsmXLDqljE1aE8i3S2i8tvcC5CXHOFHG/lBGpWpRhiMAsyoaUjVZM7HqKJNbyzgQ5KgXzk6QF7VhHnIz1Hjbu29DYHzEYyUuv
sxZy7mQGYSHcTgBWUxqTKnl0ImMwj7Ti07JnzPmOR2n4xONin/fkjPjhIocSltjZibT3rqu6Q+RUuWOKQjKk78Z0a5vctAv8FNU4F92iOsSyj1WAejQv7GY8
dClIJMdbhKFTBjEHMD8aLVUGN/GprlPXRv2981D1ydnWNjz5APOb6C5VHbtK2SzCaji2p9B5kWCip/UBXMcp4pRdprjxerPgD5KyhR/Z/XUMT62q9bbMCXwq
4xFsM2Pknh/zn3cXuXsHHqDnFwWFedTOLmxI+4PvFMMzzPVVKSI2+OJw7fN2S1anqyeDTJd3TT5wYiIzqjRBUaB4LXmye/ORweky5Ij48bhUF7ixgLVaxGU7
LYUZyIjJohclwh90ZtWVnGMZ0VEVOThHcCDxU6iFP+c7OW+bkLJZnfQfejIQ1siAEuUvGujD6hloRYqUZkQu+YPEPuIggmRJld5fCvyAlmWwrKEisj26hStp
T43w7AkjP5NyvMshI0YkqgYVtErZA6ZKinzVH7wKtU7uZ2Wz6cCJ3OOyQHXJXS16hmrdPKL4lthhng1cSuc9BQepiSnd856EFA4crZTpOiS6/73j3SOjd+Gg
V+KvoNieKDYguo+cYTBKWc0BoRilSVvCI5ImgEMclls8bZG3DjxmvqpQxoB/eEFQl3ShEYQ0r7RWRbYKfmoK4Uj8bSEb0qy4VPeduUyoml5kxb2c5BYMbjc9
q14NBt52wflrRr6m+lJdhkcvHmgvVgreOAql2ahPrgddb2hebV9w83nGD94zGuHfNhRacRrVvwgMTmyMJ6aPybYnIa6RJkkRpZnXi5MM+k17I8KJY3sWgtpO
iMWrHT5A8FRpl8vt33VHk8vDldgD47zq8X9jneKxcWbkW68MbA2QXgVs0uxj13jGCKvGiv9rO4DORA2XcJ0exAAzbeVLByjyO36exQkl4121LJKdiIcTuSUL
+T4wSha2XHQvYEfPuCI01j1+9xRSSkzvNgWJVqUYXdeyR8fHXbnbg+MRDzzYPfDwtO6k7F04PfXM7wz/bmwcEEt2kCj+DC38ZtBFKaL0/PHaM5k0V4qvwygr
BUrhD2BEu2qo8ZwlYLcJkM8I0gw7MpPoJ/N4/IMDvqydAzRUl3x5ttsCfpmePemysIxd3CteYIbDVTl+r6bwVODS3dO1pZVO5ERFxYT8u7tomT4l5ZpV0uRG
WvnkDOY4m+jIeZIFKwS4Te46g1T5ROsYpv+esNWTviYn+Y4i1LuWJqf0pr9gDvSQoDHKEj5qek6SZqvapzGHcaOUFNPo+1xEVR5C5hiusA6MbIA3v7tCnfZj
U27ueKa88pkTDNm8P9UHBD4ZlRux7U9L9aCJ5FMfKPWRvkZqXdhwbkbuw3bGITZXOeYpeUPorbDls+ECsxvt7q52Gf3g05LRh+QiKtFilMnYKbpxYT8d6rZs
Z9rARXYkiFocOyZcurGEa1SrnZaKpKdC5gp6qor8yGTSEEGM+ldyZjv+Pmf7Tp4Uk3HWfqxLzITbbSwRXoZtzvWBeGLdhQs5LLxc+sCLvof8EmjTffpg3nl6
Tmuw23D1ubKcmCliNj0ZB1teQxuw+FzKzsI9RhcbJDotND9cclBBAO+6vVv5rgWuv796Os9UYHm3FyvfMc8taFYPmQQ0jWdsavrHnsUeadE43N6yX9QA60it
SiWVS4ocdKYHD+Y0VvyItvmFQMWo7cCWcLvD+UELVsGnTHter/qpSlq/0qbijrdqX0eKQEh2xWTvyVousHa3wKma3oyNM7y4bWcrm6pHDsCNUcembip9EJi/
YkPYfw3+jKJS1eSCduFWcVKnXC0nQCmmVZn7M93WuJI91zNK6PrUg+eRve/rkjUDpLWOUF/NK+9F5k0B2ASvWVAoXbinACRvKK+0EdXE/M7NVN7obXneV4cz
rCJb4Iyt7412dPlGVKrPerm0yan5iwZhEp0gFpi7b4c5BXCRUA+K4rTJJl0donnIQukDihpt8b3gGGgmw9E/YaKpb3hvqdDbqclI+iXUxPSx1p0yF3twIBK4
amApNNsMIvDQMqLtkFN5UVU+QF4cgGq6Xhw2TtPFsxbRkpc2PJ4pEPwEXMUK5pr6XSUqOQsjn59CHkpdRc4EbOKYTXtv7qW5QzKNAH/9ZtvHki6W/bJBYXJ9
yRT7mtHB4FKAJ5Bw9Fyl5ac8LQ65q9IxIraQJevoeQ5k9q9dMSwhB7Uscjiyf177JgjNSUWF3y3hY+rdiLoLcIMQZlPkp07yo3XOWcbPf3xifLp/auweiU/t
yJKLGXTkfNNSjmFHu+ZnlSS+kZEp6tnFk54E8tsk6KgmJ2WmkqQft19u5T9/953gnON/+Vs5/TXO/nqn88z+2pcMfGWheQeddZZamN40bF38mVJyh3IaBoAS
t2eG8yOm4f1MsXh7m3dksc6yzXxZjqbbgZ19ewALg8t6cB8DRCukuj0WJcdCqYdkOt4zzvGfy51qQ7FNC+jR3fxQD0tiZWmdTd0EzYOt4454UjW73cyaXkzG
Um9o3jUCVEtrf7hDc/tmgdDa/UV0tOzmNq0yEUY7Ad1Dqz8nS8NtqyPm0fNM5vUNMjqrfkLa8JMbs9C/H874RRcg37Ln0Vhawx0MxOeOCQ+DEyO6eI1+wg1A
CczlKpcxBxSFQhbY4qFMginfusmiVO/xxE0BlqjBMDy2N/WUC0jhk/JtNSDoA/ZRFw8zRV8/CMkN/dy+DFdKyeu5x2dOOFdnYGWOt2v0SoJOWRUSHRHd9CXN
qigIc4vL8NiiS2i88i5ShwoQ2mXdgSRcRus1FzlEX2ETiVdKwbl395Qg8+jsszMyZiF5Ds/BbpR5XLIVyQqPaYjtw58GTb+4y8k/ea4AJHD61og7uYcfEOqC
BEzgRvjXQcjFGrKK9ppqwRR2f3DlNC9TZ99PpRZTax+hHQCl+CF588HgJwNajPkZ94dfLZQMc4LeYAcUplO9XI4vO5icWN6U1JzgGKMkjM5T/niwFHsNp7zy
cC+5smiJkE+Ma1xu/GKXG0vyHbmpHrVNTTWvVSi85gPs4EEkJ3U2mBOI2omDP4+SlIlSS6pWFDN5qkd2eNNo9l6qKh2kESRA1jfCEuFyZfMM/CbJejXbj+Za
ngSYSDslqdazIO209G/aoTY95wUnpX3cNaXna6FcYQMwuQZLGgwb+uxeoCXvaRBtaNftPfO0TsMFsei3O3bmGfI3xDUJ9ERqv+5xg3fhmMx6TdnOZpkp/WRZ
2AGCYwQWOaVFcpWo1Z0v01uitPRCNvGSDs94T8a8i++cEIrBzql0BqUr8+TW7NdYW7FugDseggPy7jrWcGRIP9oeWSGfkh7w8Yzl/Tmf7+csnp+/IE57tqGf
zx6M477Tx4K8/S/wfPsvylVqsYzNo8hlPbnxtCBULagnneGMGwQ94DSGz4gH+JTmp7cjmsoc4oZIVd5Aww9MtBT1du8YDGvYuarJeLD9xTOAG6lLPjIeMkgm
TFY8tWLW7D6eLmUiK7PM42bkQdbYT7DTRaENzPI2Bwv7gWcYnsa8UsxRMaaI1uqNuWVvl/3Ly9sMLXao2VdObxrJgdGVgoh2ylMmnhbJZB6edFSKeUbA+bHC
Th4OGt3jPbYT9xWG2YXP/JhwMNZYNjZyN5cP04N0K7oY6Z/uEctomuaADzPi+Nv8/ex+Y7gKZgHrdGmfpmrKWnawwjO6v+/R1l/WKqeABTyjYD2lVN6KmIrY
/0Wqm/9Yq0DUrVpUt6YHOfcsW787M+P6e+bbCWPUbBZR/TqpA7N2oFeK37jawaJPdF7h7fFeOKDhYsAePgsnIboHaPaS6q+ZHjNIegWec8rgRlZhjnh9QqWh
xhwmtnKMr7qSx6EqOS8PLfRHOW4byXSCbTbrbXeFVvkpsi+tudFz0/S5T7wfUinIMXfwC9SQXCcFfk01UWVRIFAV2hj8Ms2b08OgVgiGjGZ71hBLeiRY3ZNs
m2zI6t83DjD593Y2MoDrkLh1mEh39oevdx4xPDUE2W8NtdP7mIwBCV/63XswYjhsSSfy54HPC8+CLKhzU3yihO2RcNeQzEWvn/wLXUzEBltw/6QqEwy+yejY
Bja4DAjGdWiDAlc87jMEd/4o1qF+mIV4bFiYTmEMoCvDyzi+OTqc2YPi/nZn+nTgOrpbQsZTujDUHuj+KTdvJSMePtcY5y8OOJbFVdWNb66bcYtM485zfGp8
XuNYw9LEJrYkspsp1d590hbnbCcVzu5Y3cQIK//oV4qRJJzNs40Q0EN6b6uEJCjrKGRLIoD/yGQMK72wkWWt7dBUb6nNGI7TD/RaOJsBOGmJ7XfI9GQh0qhb
86XJq2oI0s/0FgHLNNDbnyKULdXwnv4W8BeD7d+7tKOcLjc5SKmW/pPvXgmBJnhhLx00mJxmdEWDOJ+n7Zu0PZMD3b4JPun1qFHkzuF0k7tR/t7HRLC1Gtg+
GlgAFpk70KTMewDrnj3BwxSOpV3xLbHVdoaiQzfdXuDqAjt/WvmhW4nv0bUGBlBaL1J8BF2XWf5G4kPwTT3SmqyHGYhTne6JND/xWsu1VrHO1R/JHiTfCnxh
LmeUnp9CN4coBiJRrhCX3uPMBPFWRHzQIDO6AW4NuH/qelof9Uz3tIMR0Ua5LeFBJ3P/+cmz7LicYp9Wt3lCztkU4SefPEdc8tVzGYlJ1VEFrcnGI9YPwDid
Fs+FoT6c2mrKJu/5ur6MjLm34G7Aw92WXjZvuqcG6TsrUM5coDUINEccyluG6dQ21kxP+95+RlGq1unKlQY1x31pNzOMrUrjxIyYYod6KHGE9aSLmxX6tbhq
b2e9ceUIS2zJJwm+4CHaiLB3ZQjLitulvNOUTierPHS8RgzgN/Qok2mYX8R9u4xhFdDX170AlaRZU8ml0K9z+aIiw4SAT6efrwgE+/0Bte3V8O/b3/Jv4/U/
eayqU2KUFL3qvLwryWMIhx4k+SVEPFhF05GQGeeI7OyRbTGSQUt3rG9vs4s6ItjFBaaTB0L4pAnlizbpfeEh1XaaRabZtTQo5jRg+vmw/1VK/V7mbilvsYj2
J84mdEipWeV2Y0443IjQQqS6MMmrxdP/DnxFWaYoBFUJ1Eq+9ADbD/T+UuuPk+E/YPbr5x6WSFvYO7s0I0tk+4aN12iX7Ww0GUgeW8LAiMSvK6UdlWwPNtEu
7ST2tN5UeUs3GJK6Gbnk7Z0/1ouPrVLrD1Xa0jcbkPhWmfT3P3p3v/v7zH4NpS1d2IDExciYC5Xv3m4faIKNpzAebNg+2rgxz/Qb52lQ6/V6lnmuevGj8CCK
Cg1VMe9xNcA90Q4RobOwbX2frggPywoS0iKtRbOjBeQK2IX7y4SUlKtZ+UsJXZ/q9/zoo+rq6LvOkSI8HXCzqRLt9YSIwj4hQNRYhNtVEz1VW4eqLuueoPO0
izU3/3tgAqJ1GiuNf6f+SWs63Zig1rsGpF7PmFVBbuD9q5596o9tJdxUOTxx3+n5bH9YnRvTkKY/3LKvOD09iB3O6KkKaSM3bluoQIpec7tRBiplOSXN4kI0
vcUprjE0+miFlQTH9HFRPpXl1WlJdITsnHOra4Oj4smmnpq0czf4gL4jaaQGzYMF9d2G0grnvMRuX9z+aGCkHW0j7R65c4SG0MKHuyaLu4qDPZpORIU9J1nu
eS4B
`.replace(/\s+/g, "");
const INDEX_HTML = zlib.brotliDecompressSync(Buffer.from(INDEX_BROTLI_B64, "base64")).toString("utf8");

app.use(express.json({ limit: "256kb" }));

const cache = new Map();
const lastGood = new Map();
const lastGoodWallet = new Map();
const walletHistory = new Map();
const universeHistory = new Map();
const MAX_ROTATION_SNAPSHOTS = 240;
const MIN_MONEY_FLOW_USD = 200000;

const num = (v, fallback = 0) => {
  const x = Number(v);
  return Number.isFinite(x) ? x : fallback;
};

const clamp = (x, a, b) => Math.max(a, Math.min(b, x));
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function cached(key, ttl, fn) {
  const hit = cache.get(key);
  if (hit && Date.now() - hit.time < ttl) return hit.value;
  const value = await fn();
  cache.set(key, { time: Date.now(), value });
  return value;
}

async function fetchText(url, options = {}) {
  const controller = new AbortController();
  const timeoutMs = num(options.timeout, 15000);
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  const { timeout, signal: callerSignal, ...rest } = options;
  if (callerSignal?.aborted) controller.abort();
  try {
    const r = await fetchImpl(url, {
      ...rest,
      signal: controller.signal,
      headers: {
        "User-Agent": "Mozilla/5.0 ALI-Flow-Radar/5.12",
        Accept: "text/html,text/plain,text/csv,application/json,*/*",
        ...(options.headers || {})
      }
    });
    const text = await r.text();
    if (!r.ok) throw new Error(`HTTP ${r.status}: ${text.slice(0, 140)}`);
    return text;
  } finally {
    clearTimeout(timer);
  }
}

async function fetchJson(url, options = {}) {
  const text = await fetchText(url, options);
  try {
    return JSON.parse(text);
  } catch {
    throw new Error("Invalid JSON response");
  }
}

const BINANCE_REST_BASES = [
  "https://data-api.binance.vision",
  "https://api.binance.com",
  "https://api1.binance.com",
  "https://api2.binance.com",
  "https://api3.binance.com"
];

async function binanceJson(pathname) {
  let lastError = null;
  for (const base of BINANCE_REST_BASES) {
    try {
      return await fetchJson(base + pathname);
    } catch (e) {
      lastError = e;
    }
  }
  throw lastError || new Error("All Binance market-data endpoints failed");
}

async function hyper(body) {
  return fetchJson("https://api.hyperliquid.xyz/info", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body)
  });
}

async function mapLimit(items, limit, worker) {
  const out = new Array(items.length);
  let next = 0;
  async function run() {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      out[i] = await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, run));
  return out;
}

function ema(values, period) {
  if (!values.length) return null;
  const k = 2 / (period + 1);
  let e = values[0];
  for (let i = 1; i < values.length; i++) e = values[i] * k + e * (1 - k);
  return e;
}

function rsi(values, period = 14) {
  if (!values || values.length <= period) return 50;
  let gains = 0;
  let losses = 0;
  const start = values.length - period;
  for (let i = start; i < values.length; i++) {
    const d = values[i] - values[i - 1];
    if (d >= 0) gains += d;
    else losses += Math.abs(d);
  }
  if (losses === 0) return 100;
  const rs = (gains / period) / (losses / period);
  return 100 - 100 / (1 + rs);
}

function atrFromKlines(rows, period = 14) {
  if (!rows || rows.length < 2) return 0;
  const trs = [];
  for (let i = 1; i < rows.length; i++) {
    const h = num(rows[i][2]);
    const l = num(rows[i][3]);
    const pc = num(rows[i - 1][4]);
    trs.push(Math.max(h - l, Math.abs(h - pc), Math.abs(l - pc)));
  }
  const x = trs.slice(-period);
  return x.length ? x.reduce((a, b) => a + b, 0) / x.length : 0;
}

function returnPct(values, barsBack) {
  if (!values.length || values.length <= barsBack) return 0;
  const last = values.at(-1);
  const prev = values.at(-(barsBack + 1));
  return prev ? ((last - prev) / prev) * 100 : 0;
}

/* =========================================================
   HEALTH
========================================================= */

app.get("/api/health", (req, res) => {
  res.json({
    ok: true,
    version: "5.12",
    app: "ALI Flow Radar",
    universe: "Dynamic Top 20 by filtered Money Flow; technical advisor is report-only",
    strategy: "MONEY_FLOW_ONLY",
    minMoneyFlowUsd: MIN_MONEY_FLOW_USD,
    advisorTradeAuthority: false,
    time: new Date().toISOString()
  });
});

/* =========================================================
   BINANCE MARKET
========================================================= */

app.get("/api/binance", async (req, res) => {
  const symbols = String(req.query.symbols || "BTCUSDT,ETHUSDT")
    .split(",")
    .map(x => x.trim().toUpperCase())
    .filter(Boolean)
    .slice(0, 40);

  try {
    const rows = await cached("binance:all24h", 2500, () =>
      binanceJson("/api/v3/ticker/24hr")
    );

    const wanted = new Set(symbols);
    const data = (Array.isArray(rows) ? rows : [])
      .filter(x => wanted.has(x.symbol))
      .map(x => ({
        symbol: x.symbol,
        lastPrice: num(x.lastPrice),
        openPrice: num(x.openPrice),
        highPrice: num(x.highPrice),
        lowPrice: num(x.lowPrice),
        priceChangePercent: num(x.priceChangePercent),
        quoteVolume: num(x.quoteVolume)
      }));

    res.json(data);
  } catch (e) {
    res.status(502).json({ error: String(e) });
  }
});

async function getFlowForSymbol(symbol) {
  return cached(`flow:${symbol}`, 2200, async () => {
    const trades = await binanceJson(
      `/api/v3/aggTrades?symbol=${encodeURIComponent(symbol)}&limit=500`
    );

    let buy = 0;
    let sell = 0;
    let oldest = Infinity;
    let newest = 0;

    for (const t of trades || []) {
      const value = num(t.p) * num(t.q);
      if (t.m) sell += value;
      else buy += value;
      oldest = Math.min(oldest, num(t.T));
      newest = Math.max(newest, num(t.T));
    }

    const total = buy + sell;
    const rawBuyRatio = total ? (buy / total) * 100 : 50;
    const rawNetFlow = buy - sell;
    const rawFlowIntensityPct = total ? (rawNetFlow / total) * 100 : 0;

    // GLOBAL MONEY-FLOW FLOOR: anything below $200,000 is neutral everywhere.
    const minDecisionUsd = MIN_MONEY_FLOW_USD;
    const meaningfulFlow = Math.abs(rawNetFlow) >= minDecisionUsd;
    const netFlow = meaningfulFlow ? rawNetFlow : 0;
    const buyRatio = meaningfulFlow ? rawBuyRatio : 50;
    const flowIntensityPct = meaningfulFlow ? rawFlowIntensityPct : 0;

    return {
      symbol,
      takerBuy: buy,
      takerSell: sell,
      netFlow,
      buyRatio,
      flowIntensityPct,
      flowScore: meaningfulFlow
        ? clamp(50 + (buyRatio - 50) * 1.35 + flowIntensityPct * 0.9, 0, 100)
        : 50,
      rawNetFlow,
      rawBuyRatio,
      rawFlowIntensityPct,
      minDecisionUsd,
      meaningfulFlow,
      sampleTrades: Array.isArray(trades) ? trades.length : 0,
      sampleSeconds:
        newest && Number.isFinite(oldest) ? Math.max(1, (newest - oldest) / 1000) : 0
    };
  });
}

app.get("/api/flow", async (req, res) => {
  const symbols = String(req.query.symbols || "BTCUSDT,ETHUSDT")
    .split(",")
    .map(x => x.trim().toUpperCase())
    .filter(Boolean)
    .slice(0, 40);

  const rows = await mapLimit(symbols, 5, async symbol => {
    try {
      return await getFlowForSymbol(symbol);
    } catch (e) {
      return { symbol, error: String(e) };
    }
  });

  res.json(rows);
});

app.get("/api/klines", async (req, res) => {
  const symbol = String(req.query.symbol || "BTCUSDT").trim().toUpperCase();
  const interval = String(req.query.interval || "5m").trim();
  const limit = clamp(num(req.query.limit, 120), 30, 300);
  const allowed = new Set(["1m", "3m", "5m", "15m", "30m", "1h", "4h"]);

  if (!/^[A-Z0-9]{5,20}$/.test(symbol)) return res.status(400).json({ error: "Invalid symbol" });
  if (!allowed.has(interval)) return res.status(400).json({ error: "Invalid interval" });

  try {
    const rows = await cached(`klines:${symbol}:${interval}:${limit}`, 10000, () =>
      binanceJson(
        `/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=${limit}`
      )
    );

    res.json(
      (rows || []).map(r => ({
        openTime: num(r[0]),
        open: num(r[1]),
        high: num(r[2]),
        low: num(r[3]),
        close: num(r[4]),
        volume: num(r[5]),
        closeTime: num(r[6]),
        quoteVolume: num(r[7]),
        trades: num(r[8])
      }))
    );
  } catch (e) {
    res.status(502).json({ error: String(e) });
  }
});

/* =========================================================
   DYNAMIC TOP-20 EARLY-FLOW UNIVERSE
========================================================= */

const EXCLUDED_BASES = new Set([
  "USDC", "FDUSD", "TUSD", "USDP", "DAI", "BUSD", "EUR", "TRY", "BRL",
  "AEUR", "EURI", "PAXG", "WBTC"
]);

function isEligibleUSDT(symbol) {
  if (!symbol || !symbol.endsWith("USDT")) return false;
  const base = symbol.slice(0, -4);
  if (EXCLUDED_BASES.has(base)) return false;
  if (/UP$|DOWN$|BULL$|BEAR$/.test(base)) return false;
  return /^[A-Z0-9]+$/.test(base);
}

function rawToBar(r) {
  return {
    openTime: num(r[0]),
    open: num(r[1]),
    high: num(r[2]),
    low: num(r[3]),
    close: num(r[4]),
    volume: num(r[5]),
    closeTime: num(r[6]),
    quoteVolume: num(r[7]),
    trades: num(r[8]),
    takerBuyBase: num(r[9]),
    takerBuyQuote: num(r[10])
  };
}

function aggregateBars(rawRows, minutes) {
  const bucketMs = minutes * 60000;
  const buckets = new Map();

  for (const raw of rawRows || []) {
    const r = Array.isArray(raw) ? rawToBar(raw) : raw;
    const key = Math.floor(r.openTime / bucketMs) * bucketMs;
    let b = buckets.get(key);

    if (!b) {
      b = {
        openTime: key,
        open: r.open,
        high: r.high,
        low: r.low,
        close: r.close,
        quoteVolume: 0,
        takerBuyQuote: 0,
        trades: 0
      };
      buckets.set(key, b);
    }

    b.high = Math.max(b.high, r.high);
    b.low = Math.min(b.low, r.low);
    b.close = r.close;
    b.quoteVolume += r.quoteVolume;
    b.takerBuyQuote += r.takerBuyQuote;
    b.trades += r.trades;
  }

  return Array.from(buckets.values()).sort((a, b) => a.openTime - b.openTime);
}

function flowFromBars(bars, count) {
  const rows = (bars || []).slice(-count);
  let total = 0;
  let buy = 0;

  for (const r of rows) {
    total += num(r.quoteVolume);
    buy += num(r.takerBuyQuote);
  }

  const sell = Math.max(0, total - buy);
  const rawBuyRatio = total ? (buy / total) * 100 : 50;
  const rawNetFlow = buy - sell;
  const rawIntensityPct = total ? (rawNetFlow / total) * 100 : 0;

  // Same global $200,000 floor for 1m/5m/15m structural flow.
  const minDecisionUsd = MIN_MONEY_FLOW_USD;
  const meaningfulFlow = Math.abs(rawNetFlow) >= minDecisionUsd;
  const netFlow = meaningfulFlow ? rawNetFlow : 0;
  const buyRatio = meaningfulFlow ? rawBuyRatio : 50;
  const intensityPct = meaningfulFlow ? rawIntensityPct : 0;

  return {
    buy,
    sell,
    total,
    netFlow,
    buyRatio,
    intensityPct,
    score: meaningfulFlow ? clamp(50 + (buyRatio - 50) * 1.75, 0, 100) : 50,
    rawNetFlow,
    rawBuyRatio,
    rawIntensityPct,
    minDecisionUsd,
    meaningfulFlow
  };
}

function atrObjects(rows, period = 14) {
  if (!rows || rows.length < 2) return 0;
  const trs = [];
  for (let i = 1; i < rows.length; i++) {
    const h = num(rows[i].high);
    const l = num(rows[i].low);
    const pc = num(rows[i - 1].close);
    trs.push(Math.max(h - l, Math.abs(h - pc), Math.abs(l - pc)));
  }
  const x = trs.slice(-period);
  return x.length ? x.reduce((a, b) => a + b, 0) / x.length : 0;
}

function lastSwing(rows, side, lookback = 12) {
  const x = (rows || []).slice(-lookback);
  if (!x.length) return null;
  if (side === "LOW") return Math.min(...x.map(r => num(r.low, Infinity)));
  return Math.max(...x.map(r => num(r.high, -Infinity)));
}

function updateUniverseHistory(symbol, flow5, flow15, side = "LONG") {
  const arr = universeHistory.get(symbol) || [];
  arr.push({
    time: Date.now(),
    flow5: num(flow5),
    flow15: num(flow15)
  });
  while (arr.length > 8) arr.shift();
  universeHistory.set(symbol, arr);

  if (arr.length < 2) return 50;
  const sameDirection = arr.filter(x =>
    side === "SHORT"
      ? x.flow5 <= 48 && x.flow15 <= 49
      : x.flow5 >= 52 && x.flow15 >= 51
  ).length;

  return (sameDirection / arr.length) * 100;
}

function timeframeTrendScore(fast, slow, atrValue) {
  if (!Number.isFinite(fast) || !Number.isFinite(slow)) return 50;

  const scale = Math.max(
    Math.abs(atrValue),
    Math.abs(slow) * 0.001,
    1e-12
  );

  return clamp(
    50 + ((fast - slow) / scale) * 12,
    0,
    100
  );
}

async function getMinuteKlines(symbol) {
  return cached(
    `universe-1m:${symbol}`,
    15000,
    () =>
      binanceJson(
        `/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=360`
      )
  );
}

async function analyzeMarketAsset(ticker) {
  const symbol = ticker.symbol;
  const raw = await getMinuteKlines(symbol);
  const one = (raw || []).map(rawToBar);

  if (one.length < 40) {
    throw new Error("Insufficient minute data");
  }

  const bars5 = aggregateBars(one, 5);
  const bars15 = aggregateBars(one, 15);
  const bars60 = aggregateBars(one, 60);

  const closes5 = bars5.map(x => x.close).filter(x => x > 0);
  const closes15 = bars15.map(x => x.close).filter(x => x > 0);
  const closes60 = bars60.map(x => x.close).filter(x => x > 0);

  const last = closes5.at(-1) || num(ticker.lastPrice);

  const flow1m = flowFromBars(one, 1);
  const flow5m = flowFromBars(one, 5);
  const flow15m = flowFromBars(one, 15);

  const flowComposite = clamp(
    flow1m.score * 0.20 +
    flow5m.score * 0.35 +
    flow15m.score * 0.45,
    0,
    100
  );

  const flowDirection =
    flowComposite >= 50
      ? "LONG"
      : "SHORT";

  const persistenceScore =
    updateUniverseHistory(
      symbol,
      flow5m.score,
      flow15m.score,
      flowDirection
    );

  const e5Fast = ema(closes5.slice(-60), 9) || last;
  const e5Slow = ema(closes5.slice(-60), 21) || last;

  const e15Fast = ema(closes15.slice(-24), 5) || last;
  const e15Slow = ema(closes15.slice(-24), 13) || last;

  const atr5 =
    atrObjects(bars5, 14) ||
    last * 0.0045;

  const rsi5 = rsi(closes5, 14);

  const ret5m = returnPct(closes5, 1);
  const ret15m = returnPct(closes5, 3);
  const ret1h = returnPct(closes5, 12);

  const ret3h =
    returnPct(
      closes60,
      Math.min(
        3,
        Math.max(
          1,
          closes60.length - 1
        )
      )
    );

  const trend5Score =
    timeframeTrendScore(
      e5Fast,
      e5Slow,
      atr5
    );

  const trend15Score =
    timeframeTrendScore(
      e15Fast,
      e15Slow,
      atr5 * 1.8
    );

  const trend1hScore =
    clamp(
      50 +
      ret1h * 6 +
      ret3h * 2.5,
      0,
      100
    );

  let rsiScore = 50;

  if (rsi5 >= 50 && rsi5 <= 66) {
    rsiScore =
      70 +
      (rsi5 - 50) * 1.6;
  } else if (rsi5 > 66 && rsi5 <= 72) {
    rsiScore =
      95 -
      (rsi5 - 66) * 5;
  } else if (rsi5 > 72) {
    rsiScore =
      clamp(
        65 -
        (rsi5 - 72) * 5,
        10,
        65
      );
  } else if (rsi5 >= 42) {
    rsiScore =
      45 +
      (rsi5 - 42) * 2.5;
  } else {
    rsiScore =
      clamp(
        45 -
        (42 - rsi5) * 2.2,
        10,
        45
      );
  }

  const qv =
    one.map(
      x => x.quoteVolume
    );

  const recent5 =
    qv
      .slice(-5)
      .reduce(
        (a, b) => a + b,
        0
      );

  const prior20 =
    qv.slice(-25, -5);

  const avg5 =
    prior20.length
      ? prior20.reduce(
          (a, b) => a + b,
          0
        ) /
        Math.max(
          1,
          prior20.length / 5
        )
      : recent5 || 1;

  const volumeRatio =
    avg5
      ? recent5 / avg5
      : 1;

  const volumeScore =
    clamp(
      48 +
      (volumeRatio - 1) * 22,
      0,
      100
    );

  const technicalScore =
    clamp(
      trend5Score * 0.28 +
      trend15Score * 0.28 +
      trend1hScore * 0.18 +
      rsiScore * 0.16 +
      volumeScore * 0.10,
      0,
      100
    );

  const distanceAtr =
    atr5
      ? (last - e5Fast) /
        atr5
      : 0;

  let chasePenalty = 0;

  if (distanceAtr > 0.65) {
    chasePenalty +=
      Math.min(
        22,
        (distanceAtr - 0.65) * 18
      );
  }

  if (ret15m > 2.2) {
    chasePenalty +=
      Math.min(
        15,
        (ret15m - 2.2) * 5
      );
  }

  if (rsi5 > 72) {
    chasePenalty +=
      Math.min(
        18,
        (rsi5 - 72) * 2.5
      );
  }

  const earlyEntryScore =
    clamp(
      88 -
      Math.max(
        0,
        distanceAtr - 0.15
      ) * 24 -
      Math.max(
        0,
        ret15m - 0.7
      ) * 11 -
      Math.max(
        0,
        rsi5 - 66
      ) * 2 +
      Math.max(
        0,
        volumeRatio - 1
      ) * 8,
      0,
      100
    );

  const technicalState =
    e5Fast > e5Slow &&
    e15Fast > e15Slow &&
    ret1h > -0.8
      ? "BULLISH"
      : e5Fast < e5Slow &&
        e15Fast < e15Slow &&
        ret1h < 0.8
      ? "BEARISH"
      : "MIXED";

  const setupType =
    flowDirection === "LONG"
      ? (
          flow15m.score >= 56 &&
          flow5m.score >= 57 &&
          ret15m <= 1.6 &&
          distanceAtr <= 0.65
            ? "ACCUMULATION"
            : flow15m.score >= 54 &&
              flow5m.score >= 53 &&
              flow1m.score < 50 &&
              Math.abs(distanceAtr) <= 0.55
            ? "PULLBACK"
            : "INFLOW"
        )
      : (
          flow15m.score <= 44 &&
          flow5m.score <= 43 &&
          ret15m >= -1.6 &&
          distanceAtr >= -0.65
            ? "DISTRIBUTION"
            : flow15m.score <= 46 &&
              flow5m.score <= 47 &&
              flow1m.score > 50 &&
              Math.abs(distanceAtr) <= 0.55
            ? "BOUNCE"
            : "OUTFLOW"
        );

  return {
    symbol,
    lastPrice: num(
      ticker.lastPrice,
      last
    ),
    priceChangePercent24h:
      num(
        ticker.priceChangePercent
      ),
    quoteVolume24h:
      num(
        ticker.quoteVolume
      ),
    flow1m,
    flow5m,
    flow15m,
    flowComposite,
    flowDirection,
    persistenceScore,
    ema5m9: e5Fast,
    ema5m21: e5Slow,
    ema15m5: e15Fast,
    ema15m13: e15Slow,
    rsi14: rsi5,
    ret5m,
    ret15m,
    ret1h,
    ret3h,
    atr: atr5,
    atrPct:
      last
        ? (atr5 / last) * 100
        : 0,
    volumeRatio,
    volumeScore,
    trend5Score,
    trend15Score,
    trend1hScore,
    technicalScore,
    technicalState,
    distanceAtr,
    chasePenalty,
    earlyEntryScore,
    setupType,
    swingLow:
      lastSwing(
        bars5,
        "LOW",
        12
      ),
    swingHigh:
      lastSwing(
        bars5,
        "HIGH",
        12
      ),
    netFlow1m:
      flow1m.netFlow,
    netFlow5m:
      flow5m.netFlow,
    netFlow15m:
      flow15m.netFlow,
    rawNetFlow1m:
      flow1m.rawNetFlow,
    rawNetFlow5m:
      flow5m.rawNetFlow,
    rawNetFlow15m:
      flow15m.rawNetFlow,
    minDecisionUsd1m:
      flow1m.minDecisionUsd,
    minDecisionUsd5m:
      flow5m.minDecisionUsd,
    minDecisionUsd15m:
      flow15m.minDecisionUsd
  };
}

function marketRegimeFromBTC(btc) {
  if (!btc) {
    return {
      state: "NEUTRAL",
      score: 50,
      reason: "BTC money-flow data unavailable"
    };
  }

  // Trading regime is intentionally Money-Flow-only. Technical analysis is advisor/report only.
  const score = clamp(num(btc.flowComposite, 50), 0, 100);
  const state = score >= 58 ? "RISK_ON" : score <= 42 ? "RISK_OFF" : "NEUTRAL";

  return {
    state,
    score,
    btcFlow1m: btc.flow1m?.score ?? 50,
    btcFlow5m: btc.flow5m?.score ?? 50,
    btcFlow15m: btc.flow15m?.score ?? 50,
    btcTechnical: btc.technicalScore ?? 50,
    btcTrend: btc.technicalState,
    technicalUsedForTrading: false,
    reason: `${state}: BTC Money Flow ${num(btc.flowComposite, 50).toFixed(0)} (technical ignored for trading)`
  };
}

app.get(
  "/api/universe",
  async (
    req,
    res
  ) => {
    const limit =
      clamp(
        num(
          req.query.limit,
          20
        ),
        5,
        20
      );

    const scan =
      clamp(
        num(
          req.query.scan,
          32
        ),
        24,
        36
      );

    try {
      const result =
        await cached(
          `universe:v512-mf200k:${limit}:${scan}`,
          12000,
          async () => {
            const tickers =
              await cached(
                "universe:tickers",
                5000,
                () =>
                  binanceJson(
                    "/api/v3/ticker/24hr"
                  )
              );

            const all =
              Array.isArray(
                tickers
              )
                ? tickers
                : [];

            const candidates =
              all
                .filter(
                  x =>
                    isEligibleUSDT(
                      x.symbol
                    )
                )
                .filter(
                  x =>
                    num(
                      x.quoteVolume
                    ) >
                    0
                )
                .sort(
                  (
                    a,
                    b
                  ) =>
                    num(
                      b.quoteVolume
                    ) -
                    num(
                      a.quoteVolume
                    )
                )
                .slice(
                  0,
                  scan
                );

            const btcTicker =
              all.find(
                x =>
                  x.symbol ===
                  "BTCUSDT"
              ) || {
                symbol:
                  "BTCUSDT",
                lastPrice:
                  0,
                quoteVolume:
                  0,
                priceChangePercent:
                  0
              };

            const analyzed =
              await mapLimit(
                candidates,
                6,
                async ticker => {
                  try {
                    return await analyzeMarketAsset(
                      ticker
                    );
                  } catch {
                    return null;
                  }
                }
              );

            let btc =
              analyzed.find(
                x =>
                  x?.symbol ===
                  "BTCUSDT"
              ) ||
              null;

            if (!btc) {
              try {
                btc =
                  await analyzeMarketAsset(
                    btcTicker
                  );
              } catch {}
            }

            const marketRegime =
              marketRegimeFromBTC(
                btc
              );

            const valid =
              analyzed.filter(
                Boolean
              );

            const volumes =
              valid
                .map(
                  x =>
                    x.quoteVolume24h
                )
                .filter(
                  x =>
                    x > 0
                );

            const maxLog =
              Math.max(
                1,
                ...volumes.map(
                  v =>
                    Math.log10(
                      v + 1
                    )
                )
              );

            const minLog =
              volumes.length
                ? Math.min(
                    ...volumes.map(
                      v =>
                        Math.log10(
                          v +
                            1
                        )
                    )
                  )
                : maxLog;

            const maxAbsFlow = Math.max(
              MIN_MONEY_FLOW_USD,
              ...valid.map(x => Math.max(
                Math.abs(num(x.netFlow1m)),
                Math.abs(num(x.netFlow5m)),
                Math.abs(num(x.netFlow15m))
              ))
            );

            for (const x of valid) {
              const lv = Math.log10(x.quoteVolume24h + 1);
              x.liquidityScore = maxLog === minLog
                ? 70
                : clamp(((lv - minLog) / (maxLog - minLog)) * 100, 0, 100);

              const flowCandidates = [
                { window: "15m", net: num(x.netFlow15m), meaningful: !!x.flow15m?.meaningfulFlow },
                { window: "5m", net: num(x.netFlow5m), meaningful: !!x.flow5m?.meaningfulFlow },
                { window: "1m", net: num(x.netFlow1m), meaningful: !!x.flow1m?.meaningfulFlow }
              ];
              const anchor = flowCandidates.find(f => f.meaningful && Math.abs(f.net) >= MIN_MONEY_FLOW_USD) || null;
              x.meaningfulMoneyFlow = !!anchor;
              x.moneyFlowAnchor = anchor?.window || "NONE";
              x.moneyFlowThresholdUsd = MIN_MONEY_FLOW_USD;
              x.flowMagnitudeUsd = Math.max(...flowCandidates.map(f => Math.abs(f.net)), 0);
              x.moneySide = anchor ? (anchor.net < 0 ? "SHORT" : "LONG") : "FLAT";

              x.directionalFlowScore = x.moneySide === "SHORT"
                ? 100 - x.flowComposite
                : x.moneySide === "LONG"
                ? x.flowComposite
                : 50;

              // Kept for Advisor/display only. It is not used by selection or Demo trade direction.
              x.directionalTechnicalScore = x.moneySide === "SHORT"
                ? 100 - x.technicalScore
                : x.technicalScore;
              x.directionalEarlyEntryScore = x.earlyEntryScore;

              const magnitudeScore = x.meaningfulMoneyFlow
                ? clamp(
                    55 +
                    (Math.log10(Math.max(x.flowMagnitudeUsd, MIN_MONEY_FLOW_USD)) -
                      Math.log10(MIN_MONEY_FLOW_USD)) * 25,
                    55,
                    100
                  )
                : 0;
              x.flowMagnitudeScore = magnitudeScore;

              // Dynamic Top-20 is Money-Flow-first. Technical indicators have ZERO weight here.
              x.accumulationScore = clamp(
                x.directionalFlowScore * 0.65 +
                x.persistenceScore * 0.20 +
                magnitudeScore * 0.15,
                0,
                100
              );

              x.selectionScore = x.meaningfulMoneyFlow
                ? clamp(
                    x.directionalFlowScore * 0.55 +
                    x.persistenceScore * 0.20 +
                    magnitudeScore * 0.15 +
                    x.liquidityScore * 0.10,
                    0,
                    100
                  )
                : 0;
            }

            const qualified = valid
              .filter(x => x.meaningfulMoneyFlow && x.flowMagnitudeUsd >= MIN_MONEY_FLOW_USD)
              .sort((a, b) =>
                b.selectionScore - a.selectionScore ||
                b.flowMagnitudeUsd - a.flowMagnitudeUsd
              );

            // Never pad the Top-20 with sub-$200k noise. If fewer than 20 qualify, return fewer.
            const selected = qualified.slice(0, limit);

            return {
              generatedAt:
                Date.now(),
              scanCount:
                candidates.length,
              qualifiedCount:
                qualified.length,
              selectedCount:
                selected.length,
              marketRegime,
              methodology:
                "v5.12 FINAL: Demo direction is Money-Flow-only. Every net flow below $200,000 is neutralized before charts, ranking, entry and exit logic. Technical analysis is advisor/report only and has zero trade authority. Hard stop-loss keeps absolute priority; large opposite Money Flow requires persistence before exit. Learning records outcomes and reports them without changing the fixed core rules.",
              assets:
                selected
            };
          }
        );

      res.json(
        result
      );
    } catch (e) {
      res
        .status(
          502
        )
        .json({
          error:
            String(
              e
            )
        });
    }
  }
);

/* =========================================================
   HYPERLIQUID WALLET
========================================================= */

function portfolioWindow(
  portfolio,
  names
) {
  if (
    !Array.isArray(
      portfolio
    )
  ) {
    return null;
  }

  for (
    const name
    of names
  ) {
    const row =
      portfolio.find(
        x =>
          Array.isArray(
            x
          ) &&
          x[0] ===
            name
      );

    if (
      !row?.[1]
    ) {
      continue;
    }

    const d =
      row[1];

    const av =
      Array.isArray(
        d.accountValueHistory
      )
        ? d.accountValueHistory
        : [];

    const pnlHistory =
      Array.isArray(
        d.pnlHistory
      )
        ? d.pnlHistory
        : [];

    const first =
      av.length
        ? num(
            av[0]?.[1]
          )
        : 0;

    const last =
      av.length
        ? num(
            av.at(
              -1
            )?.[1]
          )
        : 0;

    const pnl =
      pnlHistory.length
        ? num(
            pnlHistory.at(
              -1
            )?.[1]
          ) -
          num(
            pnlHistory[0]?.[1]
          )
        : 0;

    const roi =
      first
        ? (
            (
              last -
              first
            ) /
            Math.abs(
              first
            )
          ) *
          100
        : null;

    let peak = 0;
    let maxDD = 0;

    for (
      const point
      of av
    ) {
      const value =
        num(
          point?.[1],
          NaN
        );

      if (
        !Number.isFinite(
          value
        )
      ) {
        continue;
      }

      peak =
        Math.max(
          peak,
          value
        );

      if (
        peak > 0
      ) {
        maxDD =
          Math.min(
            maxDD,
            (
              (
                value -
                peak
              ) /
              peak
            ) *
              100
          );
      }
    }

    return {
      pnl,
      roi,
      maxDrawdownPct:
        maxDD,
      volume:
        num(
          d.vlm
        )
    };
  }

  return null;
}

function fillStats(
  fills,
  days
) {
  const cutoff =
    Date.now() -
    days *
      86400000;

  const rows =
    (
      Array.isArray(
        fills
      )
        ? fills
        : []
    ).filter(
      f =>
        num(
          f.time
        ) >=
        cutoff
    );

  let closed = 0;
  let wins = 0;
  let pnl = 0;

  for (
    const f
    of rows
  ) {
    const x =
      num(
        f.closedPnl
      );

    if (
      Math.abs(
        x
      ) >
      1e-12
    ) {
      closed++;
      pnl += x;

      if (
        x > 0
      ) {
        wins++;
      }
    }
  }

  return {
    fills:
      rows.length,
    closed,
    wins,
    winRate:
      closed
        ? (
            wins /
            closed
          ) *
          100
        : null,
    closedPnl:
      pnl
  };
}

function walletScore(
  day,
  week,
  month,
  stats
) {
  let score = 50;

  const pnls =
    [
      day?.pnl,
      week?.pnl,
      month?.pnl
    ].filter(
      Number.isFinite
    );

  if (
    pnls.length
  ) {
    const positives =
      pnls.filter(
        x =>
          x > 0
      ).length;

    score +=
      (
        positives /
          pnls.length -
        0.5
      ) *
      24;
  }

  if (
    Number.isFinite(
      month?.roi
    )
  ) {
    score +=
      clamp(
        month.roi,
        -30,
        30
      ) *
      0.55;
  }

  if (
    Number.isFinite(
      stats?.winRate
    )
  ) {
    score +=
      clamp(
        stats.winRate -
          50,
        -25,
        25
      ) *
      0.5;
  }

  if (
    Number.isFinite(
      month?.maxDrawdownPct
    )
  ) {
    score +=
      clamp(
        12 -
          Math.abs(
            month.maxDrawdownPct
          ),
        -12,
        12
      ) *
      0.65;
  }

  return Math.round(
    clamp(
      score,
      0,
      100
    )
  );
}

async function walletSummary(
  user
) {
  const key =
    user.toLowerCase();

  try {
    const summary =
      await cached(
        `wallet:${key}`,
        12000,
        async () => {
          const [
            stateR,
            portfolioR,
            fillsR
          ] =
            await Promise.allSettled(
              [
                hyper({
                  type:
                    "clearinghouseState",
                  user
                }),
                hyper({
                  type:
                    "portfolio",
                  user
                }),
                hyper({
                  type:
                    "userFills",
                  user,
                  aggregateByTime:
                    true
                })
              ]
            );

          if (
            stateR.status !==
              "fulfilled" ||
            !stateR
              .value
              ?.marginSummary
          ) {
            throw new Error(
              "Hyperliquid state unavailable"
            );
          }

          const state =
            stateR.value;

          const portfolio =
            portfolioR.status ===
            "fulfilled"
              ? portfolioR.value
              : [];

          const fills =
            fillsR.status ===
            "fulfilled"
              ? fillsR.value
              : [];

          const day =
            portfolioWindow(
              portfolio,
              [
                "perpDay",
                "day"
              ]
            );

          const week =
            portfolioWindow(
              portfolio,
              [
                "perpWeek",
                "week"
              ]
            );

          const month =
            portfolioWindow(
              portfolio,
              [
                "perpMonth",
                "month"
              ]
            );

          const allTime =
            portfolioWindow(
              portfolio,
              [
                "perpAllTime",
                "allTime"
              ]
            );

          const stats30 =
            fillStats(
              fills,
              30
            );

          const positions =
            (
              state.assetPositions ||
              []
            )
              .map(
                x =>
                  x.position ||
                  x
              )
              .filter(
                p =>
                  Math.abs(
                    num(
                      p.szi
                    )
                  ) >
                  0
              )
              .map(
                p => ({
                  coin:
                    String(
                      p.coin ||
                        ""
                    ).toUpperCase(),
                  side:
                    num(
                      p.szi
                    ) >=
                    0
                      ? "LONG"
                      : "SHORT",
                  size:
                    num(
                      p.szi
                    ),
                  positionValue:
                    Math.abs(
                      num(
                        p.positionValue
                      )
                    ),
                  entryPx:
                    num(
                      p.entryPx
                    ),
                  unrealizedPnl:
                    num(
                      p.unrealizedPnl
                    ),
                  leverage:
                    p.leverage
                      ?.value !=
                    null
                      ? num(
                          p.leverage
                            .value
                        )
                      : null
                })
              );

          const score =
            walletScore(
              day,
              week,
              month,
              stats30
            );

          return {
            user,
            equity:
              num(
                state
                  .marginSummary
                  .accountValue
              ),
            positions,
            pnl: {
              day,
              week,
              month,
              allTime
            },
            stats30,
            smartScore:
              score,
            tier:
              score >= 80
                ? "A+"
                : score >=
                    70
                ? "A"
                : score >=
                    60
                ? "B"
                : score >=
                    50
                ? "C"
                : "D",
            stale:
              false,
            updatedAt:
              Date.now()
          };
        }
      );

    lastGoodWallet.set(
      key,
      summary
    );

    return summary;
  } catch (e) {
    const old =
      lastGoodWallet.get(
        key
      );

    if (old) {
      return {
        ...old,
        stale:
          true,
        staleReason:
          String(
            e
          )
      };
    }

    throw e;
  }
}

app.get(
  "/api/hyperliquid/summary",
  async (
    req,
    res
  ) => {
    const user =
      String(
        req.query.user ||
          ""
      );

    if (
      !/^0x[a-fA-F0-9]{40}$/.test(
        user
      )
    ) {
      return res
        .status(
          400
        )
        .json({
          error:
            "Invalid wallet"
        });
    }

    try {
      res.json(
        await walletSummary(
          user
        )
      );
    } catch (e) {
      res
        .status(
          502
        )
        .json({
          error:
            String(
              e
            )
        });
    }
  }
);

/* =========================================================
   TRADER DISCOVERY
========================================================= */

function perfMap(
  row
) {
  const output =
    {};

  for (
    const item
    of row
      ?.windowPerformances ||
      []
  ) {
    if (
      !Array.isArray(
        item
      ) ||
      !item[1]
    ) {
      continue;
    }

    let key =
      String(
        item[0]
      );

    if (
      key ===
      "perpDay"
    ) {
      key =
        "day";
    }

    if (
      key ===
      "perpWeek"
    ) {
      key =
        "week";
    }

    if (
      key ===
      "perpMonth"
    ) {
      key =
        "month";
    }

    if (
      key ===
      "perpAllTime"
    ) {
      key =
        "allTime";
    }

    output[
      key
    ] = {
      pnl:
        num(
          item[1].pnl
        ),
      roiPct:
        num(
          item[1].roi
        ) *
        100,
      volume:
        num(
          item[1].vlm
        )
    };
  }

  return output;
}

function traderScore(
  t
) {
  let s = 35;
  const p =
    t.performance;

  if (
    (
      p.week
        ?.pnl ||
      0
    ) >
    0
  ) {
    s += 12;
  }

  if (
    (
      p.month
        ?.pnl ||
      0
    ) >
    0
  ) {
    s += 15;
  }

  if (
    (
      p.allTime
        ?.pnl ||
      0
    ) >
    0
  ) {
    s += 12;
  }

  s +=
    clamp(
      p.month
        ?.roiPct ||
        0,
      -30,
      30
    ) *
    0.5;

  if (
    t.turnover30d <
    500
  ) {
    s += 7;
  }

  if (
    t.equity >
    100000
  ) {
    s += 5;
  }

  return Math.round(
    clamp(
      s,
      0,
      100
    )
  );
}

app.get(
  "/api/traders",
  async (
    req,
    res
  ) => {
    try {
      const rows =
        await cached(
          "leaderboard",
          10 *
            60 *
            1000,
          async () => {
            const d =
              await fetchJson(
                "https://stats-data.hyperliquid.xyz/Mainnet/leaderboard"
              );

            return (
              d.leaderboardRows ||
              []
            ).map(
              row => {
                const performance =
                  perfMap(
                    row
                  );

                const equity =
                  num(
                    row.accountValue
                  );

                const turnover30d =
                  equity
                    ? (
                        performance.month
                          ?.volume ||
                        0
                      ) /
                      equity
                    : Infinity;

                const t =
                  {
                    address:
                      row.ethAddress,
                    name:
                      row.displayName ||
                      "Anonymous",
                    equity,
                    performance,
                    turnover30d,
                    style:
                      turnover30d <
                      20
                        ? "Position"
                        : turnover30d <
                            150
                        ? "Swing"
                        : turnover30d <
                            1000
                        ? "Active"
                        : "HFT-like"
                  };

                t.discoveryScore =
                  traderScore(
                    t
                  );

                return t;
              }
            );
          }
        );

      const minEquity =
        num(
          req.query
            .minEquity,
          50000
        );

      const minPnl =
        num(
          req.query
            .minMonthPnl,
          0
        );

      const maxTurnover =
        num(
          req.query
            .maxTurnover,
          5000
        );

      const limit =
        clamp(
          num(
            req.query
              .limit,
            50
          ),
          10,
          100
        );

      const filtered =
        rows
          .filter(
            x =>
              x.address &&
              x.equity >=
                minEquity
          )
          .filter(
            x =>
              (
                x
                  .performance
                  .month
                  ?.pnl ||
                0
              ) >=
              minPnl
          )
          .filter(
            x =>
              x.turnover30d <=
              maxTurnover
          )
          .sort(
            (
              a,
              b
            ) =>
              b.discoveryScore -
              a.discoveryScore
          )
          .slice(
            0,
            limit
          );

      res.json({
        traders:
          filtered
      });
    } catch (e) {
      res
        .status(
          502
        )
        .json({
          error:
            String(
              e
            )
        });
    }
  }
);

/* =========================================================
   MONEY ROTATION
========================================================= */

function exposureSnapshot(
  summaries
) {
  const exposure =
    {};

  let gross = 0;

  for (
    const w
    of summaries
  ) {
    if (
      !w ||
      w.error
    ) {
      continue;
    }

    const weight =
      num(
        w.smartScore,
        50
      ) /
      100;

    for (
      const p
      of (
        w.positions ||
        []
      )
    ) {
      const signed =
        (
          p.side ===
          "LONG"
            ? 1
            : -1
        ) *
        p.positionValue *
        weight;

      exposure[
        p.coin
      ] =
        (
          exposure[
            p.coin
          ] ||
          0
        ) +
        signed;

      gross +=
        Math.abs(
          signed
        );
    }
  }

  return {
    time:
      Date.now(),
    exposure,
    gross
  };
}

function rotationCalc(
  before,
  after
) {
  const allCoins =
    Array.from(
      new Set([
        ...Object.keys(
          before.exposure ||
            {}
        ),
        ...Object.keys(
          after.exposure ||
            {}
        )
      ])
    );

  const net =
    allCoins
      .map(
        coin => {
          const a =
            num(
              before
                .exposure
                ?.[coin]
            );

          const b =
            num(
              after
                .exposure
                ?.[coin]
            );

          return {
            coin,
            before:
              a,
            after:
              b,
            delta:
              b -
              a
          };
        }
      )
      .filter(x => {
        const grossBase = Math.max(num(before.gross), num(after.gross), 1);
        const minRotationUsd = MIN_MONEY_FLOW_USD;
        return Math.abs(x.delta) >= minRotationUsd;
      })
      .sort(
        (
          a,
          b
        ) =>
          Math.abs(
            b.delta
          ) -
          Math.abs(
            a.delta
          )
      );

  const inflows =
    net
      .filter(
        x =>
          x.delta >
          0
      )
      .map(
        x => ({
          coin:
            x.coin,
          value:
            x.delta
        })
      )
      .sort(
        (
          a,
          b
        ) =>
          b.value -
          a.value
      );

  const outflows =
    net
      .filter(
        x =>
          x.delta <
          0
      )
      .map(
        x => ({
          coin:
            x.coin,
          value:
            Math.abs(
              x.delta
            )
        })
      )
      .sort(
        (
          a,
          b
        ) =>
          b.value -
          a.value
      );

  const source =
    outflows.map(
      x => ({
        ...x,
        remaining:
          x.value
      })
    );

  const target =
    inflows.map(
      x => ({
        ...x,
        remaining:
          x.value
      })
    );

  const paths =
    [];

  for (
    const s
    of source
  ) {
    for (
      const t
      of target
    ) {
      if (
        s.remaining <=
        0
      ) {
        break;
      }

      if (
        t.remaining <=
        0
      ) {
        continue;
      }

      const value =
        Math.min(
          s.remaining,
          t.remaining
        );

      if (
        value <= 0
      ) {
        continue;
      }

      paths.push({
        from:
          s.coin,
        to:
          t.coin,
        value
      });

      s.remaining -=
        value;

      t.remaining -=
        value;
    }
  }

  return {
    windowSeconds:
      Math.max(
        1,
        Math.round(
          (
            after.time -
            before.time
          ) /
            1000
        )
      ),
    totalIn:
      inflows.reduce(
        (
          s,
          x
        ) =>
          s +
          x.value,
        0
      ),
    totalOut:
      outflows.reduce(
        (
          s,
          x
        ) =>
          s +
          x.value,
        0
      ),
    inflows,
    outflows,
    net,
    paths:
      paths
        .filter(p => p.value >= MIN_MONEY_FLOW_USD)
        .sort(
          (
            a,
            b
          ) =>
            b.value -
            a.value
        )
        .slice(
          0,
          30
        )
  };
}

app.get(
  "/api/rotation",
  async (
    req,
    res
  ) => {
    const users =
      String(
        req.query.users ||
          ""
      )
        .split(
          ","
        )
        .map(
          x =>
            x.trim()
        )
        .filter(
          x =>
            /^0x[a-fA-F0-9]{40}$/.test(
              x
            )
        )
        .slice(
          0,
          25
        );

    if (
      !users.length
    ) {
      return res
        .status(
          400
        )
        .json({
          error:
            "No wallets"
        });
    }

    try {
      const summaries =
        await mapLimit(
          users,
          3,
          async user => {
            try {
              return await walletSummary(
                user
              );
            } catch (e) {
              return {
                user,
                error:
                  String(
                    e
                  )
              };
            }
          }
        );

      const snap =
        exposureSnapshot(
          summaries
        );

      const key =
        users
          .map(
            x =>
              x.toLowerCase()
          )
          .sort()
          .join(
            "|"
          );

      const hist =
        walletHistory.get(
          key
        ) ||
        [];

      hist.push(
        snap
      );

      while (
        hist.length >
        MAX_ROTATION_SNAPSHOTS
      ) {
        hist.shift();
      }

      walletHistory.set(
        key,
        hist
      );

      let previous =
        null;

      for (
        let i =
          hist.length -
          2;
        i >= 0;
        i--
      ) {
        previous =
          hist[i];

        if (
          snap.time -
            previous.time >=
          60000
        ) {
          break;
        }
      }

      if (
        !previous
      ) {
        return res.json({
          warmup:
            true,
          wallets:
            users.length
        });
      }

      res.json({
        warmup:
          false,
        wallets:
          users.length,
        rotation:
          rotationCalc(
            previous,
            snap
          )
      });
    } catch (e) {
      res
        .status(
          502
        )
        .json({
          error:
            String(
              e
            )
        });
    }
  }
);

/* =========================================================
   MACRO
========================================================= */

const MACRO = [
  {
    name:
      "Gold Spot",
    symbol:
      "XAUUSD",
    stooq:
      "xauusd",
    group:
      "Gold"
  },
  {
    name:
      "WTI",
    symbol:
      "CL.F",
    stooq:
      "cl.f",
    group:
      "Oil"
  },
  {
    name:
      "Brent",
    symbol:
      "CB.F",
    stooq:
      "cb.f",
    group:
      "Oil"
  },
  {
    name:
      "DXY",
    symbol:
      "DX.F",
    stooq:
      "dx.f",
    group:
      "FX"
  },
  {
    name:
      "EUR/USD",
    symbol:
      "EURUSD",
    stooq:
      "eurusd",
    group:
      "FX"
  }
];

function parseCSV(
  text
) {
  const lines =
    text
      .trim()
      .split(
        /\r?\n/
      )
      .filter(
        Boolean
      );

  if (
    lines.length <
    2
  ) {
    throw new Error(
      "No CSV data"
    );
  }

  const header =
    lines[0]
      .split(
        ","
      )
      .map(
        x =>
          x.trim()
      );

  const values =
    lines[1]
      .split(
        ","
      )
      .map(
        x =>
          x.trim()
      );

  const row =
    {};

  header.forEach(
    (
      h,
      i
    ) =>
      row[h] =
        values[i]
  );

  return row;
}

async function macroQuote(
  asset
) {
  const text =
    await fetchText(
      `https://stooq.com/q/l/?s=${encodeURIComponent(
        asset.stooq
      )}&f=sd2t2ohlcv&h&e=csv`
    );

  const row =
    parseCSV(
      text
    );

  const open =
    num(
      row.Open,
      NaN
    );

  const close =
    num(
      row.Close,
      NaN
    );

  if (
    !Number.isFinite(
      close
    )
  ) {
    throw new Error(
      "No quote"
    );
  }

  return {
    ...asset,
    price:
      close,
    changePct:
      Number.isFinite(
        open
      ) &&
      open
        ? (
            (
              close -
              open
            ) /
            open
          ) *
          100
        : null,
    time:
      [
        row.Date,
        row.Time
      ]
        .filter(
          Boolean
        )
        .join(
          " "
        )
  };
}

app.get(
  "/api/macro",
  async (
    req,
    res
  ) => {
    const out =
      [];

    for (
      const asset
      of MACRO
    ) {
      try {
        const q =
          await cached(
            `macro:${asset.symbol}`,
            30000,
            () =>
              macroQuote(
                asset
              )
          );

        lastGood.set(
          `macro:${asset.symbol}`,
          q
        );

        out.push(
          q
        );
      } catch (e) {
        const previous =
          lastGood.get(
            `macro:${asset.symbol}`
          );

        out.push(
          previous
            ? {
                ...previous,
                stale:
                  true
              }
            : {
                ...asset,
                error:
                  String(
                    e
                  )
              }
        );
      }
    }

    res.json(
      out
    );
  }
);

/* =========================================================
   IRAN MARKET
========================================================= */

const IRAN_ITEMS = [
  {
    key:
      "price_dollar_rl",
    name:
      "USD Free Market"
  },
  {
    key:
      "geram18",
    name:
      "Gold 18K"
  },
  {
    key:
      "mesghal",
    name:
      "Mesghal"
  },
  {
    key:
      "sekee",
    name:
      "Emami Coin"
  }
];

function cleanNumber(
  str
) {
  if (!str) {
    return null;
  }

  const x =
    String(
      str
    )
      .replace(
        /<[^>]+>/g,
        ""
      )
      .replace(
        /,/g,
        ""
      )
      .replace(
        /[^0-9.\-]/g,
        ""
      );

  const value =
    Number(
      x
    );

  return Number.isFinite(
    value
  )
    ? value
    : null;
}

function extractTGJU(
  html,
  key
) {
  const escaped =
    key.replace(
      /[.*+?^${}()|[\]\\]/g,
      "\\$&"
    );

  const patterns =
    [
      new RegExp(
        `data-market-row=["']${escaped}["'][\\s\\S]{0,1500}?data-price=["']([^"']+)`,
        "i"
      ),
      new RegExp(
        `${escaped}[\\s\\S]{0,1200}?<td[^>]*class=["'][^"']*(?:nf|market-value|price)[^"']*["'][^>]*>([\\s\\S]{0,100}?)<\\/td>`,
        "i"
      ),
      new RegExp(
        `/profile/${escaped}[\\s\\S]{0,1500}?([0-9]{1,3}(?:,[0-9]{3}){1,4})`,
        "i"
      )
    ];

  for (
    const regex
    of patterns
  ) {
    const m =
      html.match(
        regex
      );

    const value =
      cleanNumber(
        m?.[1]
      );

    if (
      Number.isFinite(
        value
      ) &&
      value >
        0
    ) {
      return value;
    }
  }

  return null;
}

app.get(
  "/api/iran",
  async (
    req,
    res
  ) => {
    try {
      const html =
        await cached(
          "tgju-home",
          30000,
          () =>
            fetchText(
              "https://www.tgju.org/"
            )
        );

      const data =
        [];

      for (
        const item
        of IRAN_ITEMS
      ) {
        const value =
          extractTGJU(
            html,
            item.key
          );

        const cacheKey =
          `iran:${item.key}`;

        if (
          Number.isFinite(
            value
          )
        ) {
          const row =
            {
              ...item,
              value,
              stale:
                false,
              time:
                Date.now()
            };

          lastGood.set(
            cacheKey,
            row
          );

          data.push(
            row
          );
        } else {
          const old =
            lastGood.get(
              cacheKey
            );

          data.push(
            old
              ? {
                  ...old,
                  stale:
                    true
                }
              : {
                  ...item,
                  value:
                    null,
                  error:
                    "TGJU parse unavailable"
                }
          );
        }
      }

      res.json(
        data
      );
    } catch (e) {
      res.json(
        IRAN_ITEMS.map(
          item => {
            const old =
              lastGood.get(
                `iran:${item.key}`
              );

            return old
              ? {
                  ...old,
                  stale:
                    true
                }
              : {
                  ...item,
                  value:
                    null,
                  error:
                    String(
                      e
                    )
                };
          }
        )
      );
    }
  }
);

app.get(
  "/",
  (
    req,
    res
  ) =>
    res
      .type(
        "html"
      )
      .send(
        INDEX_HTML
      )
);

app.get(
  "/index.html",
  (
    req,
    res
  ) =>
    res
      .type(
        "html"
      )
      .send(
        INDEX_HTML
      )
);

app.listen(
  PORT,
  () => {
    console.log(
      `ALI Flow Radar v5.12 FINAL MF200K + ADVISOR running on ${PORT}`
    );
  }
);
